name = "hkviz-web"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2025-08-04"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[assets]
directory = ".output/public"

[observability.logs]
enabled = true
