/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type BellhomePaintColoursSilk =
	| 'None' /* 0 */
	| 'Red' /* 1 */
	| 'White' /* 2 */
	| 'DarkGrey' /* 3 */
	| 'Bronze' /* 4 */
	| 'Blue' /* 5 */
	| 'Chrome' /* 6 */;
const BellhomePaintColoursByName: Record<BellhomePaintColoursSilk, number> = {
	None: 0,
	Red: 1,
	White: 2,
	DarkGrey: 3,
	Bronze: 4,
	Blue: 5,
	Chrome: 6,
};
export const BellhomePaintColoursSilk = {
	isFlags: false,
	byName: BellhomePaintColoursByName,
	byId: Object.fromEntries(
		Object.entries(BellhomePaintColoursByName).map(([name, id]) => [id, name] as const),
	) as Record<number, BellhomePaintColoursSilk>,
	nameList: Object.keys(BellhomePaintColoursByName) as BellhomePaintColoursSilk[],
} as const;
export const BellhomePaintColoursNumberSchemaSilk = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(6));
