/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type BelltownHouseStatesSilk = 'None' /* 0 */ | 'Half' /* 1 */ | 'Full' /* 2 */;
const BelltownHouseStatesByName: Record<BelltownHouseStatesSilk, number> = {
	None: 0,
	Half: 1,
	Full: 2,
};
export const BelltownHouseStatesSilk = {
	isFlags: false,
	byName: BelltownHouseStatesByName,
	byId: Object.fromEntries(
		Object.entries(BelltownHouseStatesByName).map(([name, id]) => [id, name] as const),
	) as Record<number, BelltownHouseStatesSilk>,
	nameList: Object.keys(BelltownHouseStatesByName) as BelltownHouseStatesSilk[],
} as const;
export const BelltownHouseStatesNumberSchemaSilk = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2));
