/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type CaravanTroupeLocationsSilk =
	| 'Bone' /* 0 */
	| 'Greymoor' /* 1 */
	| 'CoralJudge' /* 2 */
	| 'Aqueduct' /* 3 */;
const CaravanTroupeLocationsByName: Record<CaravanTroupeLocationsSilk, number> = {
	Bone: 0,
	Greymoor: 1,
	CoralJudge: 2,
	Aqueduct: 3,
};
export const CaravanTroupeLocationsSilk = {
	isFlags: false,
	byName: CaravanTroupeLocationsByName,
	byId: Object.fromEntries(
		Object.entries(CaravanTroupeLocationsByName).map(([name, id]) => [id, name] as const),
	) as Record<number, CaravanTroupeLocationsSilk>,
	nameList: Object.keys(CaravanTroupeLocationsByName) as CaravanTroupeLocationsSilk[],
} as const;
export const CaravanTroupeLocationsNumberSchemaSilk = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(3));
