/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type EnvironmentTypesSilk =
	| 'Dust' /* 0 */
	| 'Grass' /* 1 */
	| 'Bone' /* 2 */
	| 'ShallowWater' /* 3 */
	| 'Metal' /* 4 */
	| 'NoEffect' /* 5 */
	| 'Moss' /* 6 */
	| 'Sand' /* 7 */
	| 'Bell' /* 8 */
	| 'WetMetal' /* 9 */
	| 'ThinMetal' /* 10 */
	| 'Wood' /* 11 */
	| 'Silk' /* 12 */
	| 'WetWood' /* 13 */
	| 'RunningWater' /* 14 */
	| 'PeakPuff' /* 15 */
	| 'FlowerField' /* 16 */;
const EnvironmentTypesByName: Record<EnvironmentTypesSilk, number> = {
	Dust: 0,
	Grass: 1,
	Bone: 2,
	ShallowWater: 3,
	Metal: 4,
	NoEffect: 5,
	Moss: 6,
	Sand: 7,
	Bell: 8,
	WetMetal: 9,
	ThinMetal: 10,
	Wood: 11,
	Silk: 12,
	WetWood: 13,
	RunningWater: 14,
	PeakPuff: 15,
	FlowerField: 16,
};
export const EnvironmentTypesSilk = {
	isFlags: false,
	byName: EnvironmentTypesByName,
	byId: Object.fromEntries(Object.entries(EnvironmentTypesByName).map(([name, id]) => [id, name] as const)) as Record<
		number,
		EnvironmentTypesSilk
	>,
	nameList: Object.keys(EnvironmentTypesByName) as EnvironmentTypesSilk[],
} as const;
export const EnvironmentTypesNumberSchemaSilk = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(16));
