/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type ExtraRestZonesSilk =
	| 'None' /* 0 */
	| 'PinstressHut' /* 1 */
	| 'SeamstressHut' /* 2 */
	| 'Bonegrave' /* 3 */
	| 'GrandGate' /* 4 */
	| 'TubeHub' /* 5 */
	| 'Organ' /* 6 */
	| 'Fleatopia' /* 7 */
	| 'FleaFestival' /* 8 */
	| 'Bellvein' /* 9 */
	| 'SlabCell' /* 10 */
	| 'Enclave' /* 11 */
	| 'CitadelShrine' /* 12 */
	| 'CoralTower' /* 13 */
	| 'BonetownBroken' /* 14 */
	| 'CoralBellshrine' /* 15 */
	| 'Bellhome' /* 16 */
	| 'Citadelstation' /* 17 */
	| 'MemoryRed' /* 18 */
	| 'AboveCradle' /* 19 */
	| 'SprintmasterCave' /* 20 */
	| 'BelltownHaunted' /* 21 */
	| 'WhiteLake' /* 22 */;
const ExtraRestZonesByName: Record<ExtraRestZonesSilk, number> = {
	None: 0,
	PinstressHut: 1,
	SeamstressHut: 2,
	Bonegrave: 3,
	GrandGate: 4,
	TubeHub: 5,
	Organ: 6,
	Fleatopia: 7,
	FleaFestival: 8,
	Bellvein: 9,
	SlabCell: 10,
	Enclave: 11,
	CitadelShrine: 12,
	CoralTower: 13,
	BonetownBroken: 14,
	CoralBellshrine: 15,
	Bellhome: 16,
	Citadelstation: 17,
	MemoryRed: 18,
	AboveCradle: 19,
	SprintmasterCave: 20,
	BelltownHaunted: 21,
	WhiteLake: 22,
};
export const ExtraRestZonesSilk = {
	isFlags: false,
	byName: ExtraRestZonesByName,
	byId: Object.fromEntries(Object.entries(ExtraRestZonesByName).map(([name, id]) => [id, name] as const)) as Record<
		number,
		ExtraRestZonesSilk
	>,
	nameList: Object.keys(ExtraRestZonesByName) as ExtraRestZonesSilk[],
} as const;
export const ExtraRestZonesNumberSchemaSilk = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(22));
