/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type FastTravelLocationsSilk =
	| 'None' /* 0 */
	| 'Bonetown' /* 1 */
	| 'Docks' /* 2 */
	| 'BoneforestEast' /* 3 */
	| 'Greymoor' /* 4 */
	| 'Belltown' /* 5 */
	| 'CoralTower' /* 6 */
	| 'City' /* 9 */
	| 'Peak' /* 11 */
	| 'Shellwood' /* 12 */
	| 'Bone' /* 13 */
	| 'Shadow' /* 14 */
	| 'Aqueduct' /* 15 */;
const FastTravelLocationsByName: Record<FastTravelLocationsSilk, number> = {
	None: 0,
	Bonetown: 1,
	Docks: 2,
	BoneforestEast: 3,
	Greymoor: 4,
	Belltown: 5,
	CoralTower: 6,
	City: 9,
	Peak: 11,
	Shellwood: 12,
	Bone: 13,
	Shadow: 14,
	Aqueduct: 15,
};
export const FastTravelLocationsSilk = {
	isFlags: false,
	byName: FastTravelLocationsByName,
	byId: Object.fromEntries(
		Object.entries(FastTravelLocationsByName).map(([name, id]) => [id, name] as const),
	) as Record<number, FastTravelLocationsSilk>,
	nameList: Object.keys(FastTravelLocationsByName) as FastTravelLocationsSilk[],
} as const;
export const FastTravelLocationsNumberSchemaSilk = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(15));
