/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type GameStateSilk =
	| 'INACTIVE' /* 0 */
	| 'MAIN_MENU' /* 1 */
	| 'LOADING' /* 2 */
	| 'ENTERING_LEVEL' /* 3 */
	| 'PLAYING' /* 4 */
	| 'PAUSED' /* 5 */
	| 'EXITING_LEVEL' /* 6 */
	| 'CUTSCENE' /* 7 */
	| 'PRIMER' /* 8 */;
const GameStateByName: Record<GameStateSilk, number> = {
	INACTIVE: 0,
	MAIN_MENU: 1,
	LOADING: 2,
	ENTERING_LEVEL: 3,
	PLAYING: 4,
	PAUSED: 5,
	EXITING_LEVEL: 6,
	CUTSCENE: 7,
	PRIMER: 8,
};
export const GameStateSilk = {
	isFlags: false,
	byName: GameStateByName,
	byId: Object.fromEntries(Object.entries(GameStateByName).map(([name, id]) => [id, name] as const)) as Record<
		number,
		GameStateSilk
	>,
	nameList: Object.keys(GameStateByName) as GameStateSilk[],
} as const;
export const GameStateNumberSchemaSilk = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(8));
