/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type GreenPrinceLocationsSilk = 'DustCage' /* 0 */ | 'Song04' /* 1 */ | 'CogDancers' /* 2 */ | 'Clover' /* 3 */;
const GreenPrinceLocationsByName: Record<GreenPrinceLocationsSilk, number> = {
	DustCage: 0,
	Song04: 1,
	CogDancers: 2,
	Clover: 3,
};
export const GreenPrinceLocationsSilk = {
	isFlags: false,
	byName: GreenPrinceLocationsByName,
	byId: Object.fromEntries(
		Object.entries(GreenPrinceLocationsByName).map(([name, id]) => [id, name] as const),
	) as Record<number, GreenPrinceLocationsSilk>,
	nameList: Object.keys(GreenPrinceLocationsByName) as GreenPrinceLocationsSilk[],
} as const;
export const GreenPrinceLocationsNumberSchemaSilk = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(3));
