/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type HazardRespawnMarker_FacingDirectionSilk = 'None' /* 0 */ | 'Left' /* 1 */ | 'Right' /* 2 */;
const HazardRespawnMarker_FacingDirectionByName: Record<HazardRespawnMarker_FacingDirectionSilk, number> = {
	None: 0,
	Left: 1,
	Right: 2,
};
export const HazardRespawnMarker_FacingDirectionSilk = {
	isFlags: false,
	byName: HazardRespawnMarker_FacingDirectionByName,
	byId: Object.fromEntries(
		Object.entries(HazardRespawnMarker_FacingDirectionByName).map(([name, id]) => [id, name] as const),
	) as Record<number, HazardRespawnMarker_FacingDirectionSilk>,
	nameList: Object.keys(HazardRespawnMarker_FacingDirectionByName) as HazardRespawnMarker_FacingDirectionSilk[],
} as const;
export const HazardRespawnMarker_FacingDirectionNumberSchemaSilk = v.pipe(
	v.number(),
	v.integer(),
	v.minValue(0),
	v.maxValue(2),
);
