/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type HeroDeathCocoonTypesSilk = 'Normal' /* 0 */ | 'Rosaries' /* 1 */ | 'Cursed' /* 2 */;
const HeroDeathCocoonTypesByName: Record<HeroDeathCocoonTypesSilk, number> = {
	Normal: 0,
	Rosaries: 1,
	Cursed: 2,
};
export const HeroDeathCocoonTypesSilk = {
	isFlags: true,
	byName: HeroDeathCocoonTypesByName,
	byId: Object.fromEntries(
		Object.entries(HeroDeathCocoonTypesByName).map(([name, id]) => [id, name] as const),
	) as Record<number, HeroDeathCocoonTypesSilk>,
	nameList: Object.keys(HeroDeathCocoonTypesByName) as HeroDeathCocoonTypesSilk[],

	hasFlag(value: number, flag: HeroDeathCocoonTypesSilk) {
		return (value & HeroDeathCocoonTypesSilk.byName[flag]) !== 0;
	},
} as const;
export const HeroDeathCocoonTypesNumberSchemaSilk = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(3));
