/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type NPCEncounterStateSilk =
	| 'None' /* 0 */
	| 'Met' /* 1 */
	| 'ReadyToLeave' /* 2 */
	| 'AuthorisedToLeave' /* 3 */
	| 'HasLeft' /* 4 */;
const NPCEncounterStateByName: Record<NPCEncounterStateSilk, number> = {
	None: 0,
	Met: 1,
	ReadyToLeave: 2,
	AuthorisedToLeave: 3,
	HasLeft: 4,
};
export const NPCEncounterStateSilk = {
	isFlags: false,
	byName: NPCEncounterStateByName,
	byId: Object.fromEntries(
		Object.entries(NPCEncounterStateByName).map(([name, id]) => [id, name] as const),
	) as Record<number, NPCEncounterStateSilk>,
	nameList: Object.keys(NPCEncounterStateByName) as NPCEncounterStateSilk[],
} as const;
export const NPCEncounterStateNumberSchemaSilk = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(4));
