/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type PermadeathModesSilk = 'Off' /* 0 */ | 'On' /* 1 */ | 'Dead' /* 2 */;
const PermadeathModesByName: Record<PermadeathModesSilk, number> = {
	Off: 0,
	On: 1,
	Dead: 2,
};
export const PermadeathModesSilk = {
	isFlags: false,
	byName: PermadeathModesByName,
	byId: Object.fromEntries(Object.entries(PermadeathModesByName).map(([name, id]) => [id, name] as const)) as Record<
		number,
		PermadeathModesSilk
	>,
	nameList: Object.keys(PermadeathModesByName) as PermadeathModesSilk[],
} as const;
export const PermadeathModesNumberSchemaSilk = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2));
