/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.

import * as v from 'valibot';

export type SethNpcLocationsSilk =
	| 'Absent' /* 0 */
	| 'Greymoor' /* 1 */
	| 'Shellwood' /* 2 */
	| 'Citadel' /* 3 */
	| 'Fleatopia' /* 4 */;
const SethNpcLocationsByName: Record<SethNpcLocationsSilk, number> = {
	Absent: 0,
	Greymoor: 1,
	Shellwood: 2,
	Citadel: 3,
	Fleatopia: 4,
};
export const SethNpcLocationsSilk = {
	isFlags: false,
	byName: SethNpcLocationsByName,
	byId: Object.fromEntries(Object.entries(SethNpcLocationsByName).map(([name, id]) => [id, name] as const)) as Record<
		number,
		SethNpcLocationsSilk
	>,
	nameList: Object.keys(SethNpcLocationsByName) as SethNpcLocationsSilk[],
} as const;
export const SethNpcLocationsNumberSchemaSilk = v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(4));
