import { execFile } from 'child_process';
import { mkdir, writeFile } from 'fs/promises';
import { dirname } from 'path';
import { promisify } from 'util';
const execFileAsync = promisify(execFile);

const DEFAULT_HEADER = `/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */`;

export async function exportFormattedJsFile(path: string, content: string, header: string = DEFAULT_HEADER) {
	await mkdir(dirname(path), { recursive: true });

	const finalContent = `${header}\n${content}`;
	await writeFile(path, finalContent, 'utf-8');
	await execFileAsync('pnpm', ['exec', 'oxfmt', path]);
}
