import { readFile, writeFile } from 'fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import path from 'path';
//import { modsRepo } from './paths.local.mts';

export const modsRepo = '<some-folder>';

const execFileAsync = promisify(execFile);

const jsonPlayerDataFilePath = path.join(modsRepo, 'HKViz.Silk/HKViz.Silk/Recording/PlayerDataFieldIds.json');

interface PlayerDataFieldJson {
	id: number;
	type: string;
}

interface PlayerDataJson {
	fields: Record<string, PlayerDataFieldJson>;
	enums: Record<string, Record<string, number>>;
}

const json = await readFile(jsonPlayerDataFilePath, 'utf-8');
const playerDataFromJson: PlayerDataJson = JSON.parse(json);
const outputFilePath = './src/lib/game-data/silk-data/player-data-silk.generated.ts';

const fieldsByType = Map.groupBy(
	Object.entries(playerDataFromJson.fields).map(([name, field]) => ({
		...field,
		name,
	})),
	({ type }) => type,
);

const sanitizeForTsTypeName = (typeName: string) => {
	const normalized = typeName
		// convert T[] → Array<T>
		.replace(/([a-zA-Z0-9_]+)\[\]/g, 'Array<$1>');

	const sanitized = normalized
		// handle <T> → OfT (with uppercase)
		.replace(/<\s*([a-zA-Z0-9_])/g, (_, c) => `Of${c.toUpperCase()}`)
		.replace(/>/g, '')
		.replace(/[^a-zA-Z0-9_]/g, '_');

	return sanitized.charAt(0).toUpperCase() + sanitized.slice(1);
};

const playerDataNameOfType = (typeName: string) => {
	return `PlayerDataFieldNameOfType${sanitizeForTsTypeName(typeName)}Silk`;
};
const playerDataFieldOfType = (typeName: string) => {
	return `PlayerDataFieldOfType${sanitizeForTsTypeName(typeName)}Silk`;
};

const playerDataValueOfType = (typeName: string) => {
	return `PlayerDataFieldValueOfType${sanitizeForTsTypeName(typeName)}Silk`;
};

const tsOutputLines: string[] = [
	`// This file is generated by scripts/silk-player-data-gen-types.mts. Do not edit manually.`,
	``,
	`
	import { Vector3 } from '../shared/vector-3';
	import { Vector2 } from '../shared/vectors';
	import {
		CollectableItemsDataSilk,
		CollectableMementosDataSilk,
		CollectableRelicsDataSilk,
		EnemyJournalKillDataSilk,
		MateriumItemsDataSilk,
		QuestCompletionDataSilk,
		QuestRumourDataSilk,
		ToolCrestsDataSilk,
		ToolItemLiquidsDataSilk,
		ToolItemsDataSilk,
	} from './types/player-data-custom-types-silk';
	`,
];

const playerDataTypeToTsTypeMap: Record<string, string> = {
	bool: 'boolean',
	int: 'number',
	float: 'number',
	string: 'string',
	enum: 'number',
	ulong: 'number',

	'list<string>': 'string[]',
	'list<int>': 'number[]',
	'int[]': 'number[]',

	'hashset<string>': 'Set<string>',
	'dictionary<string,bool>': 'Map<string, boolean>',
	'dictionary<string,int>': 'Map<string, number>',
	'wrappedvector2list[]': 'Vector2[][]',

	CollectableItemsData: 'Map<string, CollectableItemsDataSilk>',
	EnemyJournalKillData: 'Map<string, EnemyJournalKillDataSilk>',
	MateriumItemsData: 'Map<string, MateriumItemsDataSilk>',
	CollectableMementosData: 'Map<string, CollectableMementosDataSilk>',
	QuestCompletionData: 'Map<string, QuestCompletionDataSilk>',
	QuestRumourData: 'Map<string, QuestRumourDataSilk>',
	CollectableRelicsData: 'Map<string, CollectableRelicsDataSilk>',
	ToolCrestsData: 'Map<string, ToolCrestsDataSilk>',
	ToolItemLiquidsData: 'Map<string, ToolItemLiquidsDataSilk>',
	ToolItemsData: 'Map<string, ToolItemsDataSilk>',

	guid: 'string',
	vector2: 'Vector2',
	vector3: 'Vector3',
};

for (const [type, fields] of fieldsByType) {
	const typeName = sanitizeForTsTypeName(type);

	let tsType = playerDataTypeToTsTypeMap[type];
	if (!tsType) {
		console.warn(`No TS type mapping found for player data field type "${type}". Defaulting to "unknown".`);
		tsType = 'unknown';
	}

	tsOutputLines.push(
		`export type ${playerDataValueOfType(typeName)} = ${tsType};`,
		`export type ${playerDataNameOfType(typeName)} = ${fields.map((f) => `'${f.name}'`).join(' | ')};`,
		`export interface ${playerDataFieldOfType(typeName)} {
			id: number,
			name: ${playerDataNameOfType(typeName)},
			type: '${type}',
		}`,
	);
	tsOutputLines.push(``);
}

tsOutputLines.push(
	`export type PlayerDataFieldNameSilk = ${fieldsByType
		.keys()
		.map((name) => `${playerDataNameOfType(name)}`)
		.toArray()
		.join(' | ')};`,
	`export type PlayerDataFieldTypeSilk = ${fieldsByType
		.keys()
		.map((name) => `'${name}'`)
		.toArray()
		.join(' | ')};`,
	`export type PlayerDataFieldSilk = ${fieldsByType
		.keys()
		.map((name) => `${playerDataFieldOfType(name)}`)
		.toArray()
		.join(' | ')};`,
	`export type PlayerDataFieldValueSilk<TField extends PlayerDataFieldNameSilk> = ${fieldsByType
		.keys()
		.map((name) => {
			const playerDataNameType = playerDataNameOfType(name);
			return `TField extends ${playerDataNameType} ? ${playerDataValueOfType(name)} : `;
		})
		.toArray()
		.join('')} never;`,
	`export type PlayerDataFieldTypeByNameSilk<TField extends PlayerDataFieldNameSilk> = ${fieldsByType
		.keys()
		.map((name) => {
			const playerDataNameType = playerDataNameOfType(name);
			return `TField extends ${playerDataNameType} ? ${playerDataFieldOfType(name)} : `;
		})
		.toArray()
		.join('')} never;`,
);

tsOutputLines.push(
	``,
	`const fieldsByName = {`,
	...Object.entries(playerDataFromJson.fields).map(([fieldName, field]) => {
		const typeName = sanitizeForTsTypeName(field.type);
		return `${fieldName}: { 
					id: ${field.id}, 
					name: '${fieldName}',
					type: '${field.type}',
				} satisfies ${playerDataFieldOfType(typeName)} as ${playerDataFieldOfType(typeName)},`;
	}),
	`	};`,
	`export const playerDataFieldsSilk = {`,
	`	byFieldName: fieldsByName,`,
	`	byId: new Map<number, PlayerDataFieldSilk>(Object.values(fieldsByName).map(f => [f.id, f] as const)),`,
	`   list: Object.values(fieldsByName) as PlayerDataFieldSilk[],`,
	`};`,
);

await writeFile(outputFilePath, tsOutputLines.join('\n'));
await execFileAsync('pnpm', ['exec', 'oxfmt', outputFilePath]);

console.log('Generated player data types for Silk.');
