/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */

export type CollectableRelicNameSilk =
	| 'Bone Record Greymoor_flooded_corridor'
	| 'Bone Record Bone_East_14'
	| 'Bone Record Understore_Map_Room'
	| 'Bone Record Wisp Top'
	| 'Seal Chit Aspid_01'
	| 'Seal Chit Ward Corpse'
	| 'Seal Chit City Merchant'
	| 'Seal Chit Silk Siphon'
	| 'Weaver Totem Bonetown_upper_room'
	| 'Weaver Totem Witch'
	| 'Weaver Totem Slab_Bottom'
	| 'Weaver Record Weave_08'
	| 'Weaver Record Sprint_Challenge'
	| 'Weaver Record Conductor'
	| 'Ancient Egg Abyss Middle'
	| 'Psalm Cylinder Librarian'
	| 'Psalm Cylinder Library Roof'
	| 'Psalm Cylinder Ward'
	| 'Psalm Cylinder Grindle'
	| 'Psalm Cylinder Hang'
	| 'Librarian Melody Cylinder';

const list = [
	{
		id: 'Bone Record Greymoor_flooded_corridor',
		runtimeType: 'CollectableRelic',
		rewardAmount: 90,
		typeNameKey: 'UI.INV_NAME_R_BONE_RECORD',
		typeDescriptionKey: 'UI.INV_DESC_R_BONE_RECORD',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0002_R_bone_record_11_123x142_1',
			nameShort: 'Hornet_icon_0002_R_bone_record',
			size: {
				x: 123,
				y: 142,
			},
			padding: {
				x: 2.026751,
				y: 2.07612038,
				z: 2.04290771,
				w: 2.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0002_R_bone_record_11_123x142_1',
			nameShort: 'Hornet_icon_0002_R_bone_record',
			size: {
				x: 123,
				y: 142,
			},
			padding: {
				x: 2.026751,
				y: 2.07612038,
				z: 2.04290771,
				w: 2.02674866,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Bone Record',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0002_R_bone_record_11_123x142_1',
			nameShort: 'Hornet_icon_0002_R_bone_record',
			size: {
				x: 123,
				y: 142,
			},
			padding: {
				x: 2.026751,
				y: 2.07612038,
				z: 2.04290771,
				w: 2.02674866,
			},
		},
	},
	{
		id: 'Bone Record Bone_East_14',
		runtimeType: 'CollectableRelic',
		rewardAmount: 90,
		typeNameKey: 'UI.INV_NAME_R_BONE_RECORD',
		typeDescriptionKey: 'UI.INV_DESC_R_BONE_RECORD',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0002_R_bone_record_11_123x142_1',
			nameShort: 'Hornet_icon_0002_R_bone_record',
			size: {
				x: 123,
				y: 142,
			},
			padding: {
				x: 2.026751,
				y: 2.07612038,
				z: 2.04290771,
				w: 2.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0002_R_bone_record_11_123x142_1',
			nameShort: 'Hornet_icon_0002_R_bone_record',
			size: {
				x: 123,
				y: 142,
			},
			padding: {
				x: 2.026751,
				y: 2.07612038,
				z: 2.04290771,
				w: 2.02674866,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Bone Record',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0002_R_bone_record_11_123x142_1',
			nameShort: 'Hornet_icon_0002_R_bone_record',
			size: {
				x: 123,
				y: 142,
			},
			padding: {
				x: 2.026751,
				y: 2.07612038,
				z: 2.04290771,
				w: 2.02674866,
			},
		},
	},
	{
		id: 'Bone Record Understore_Map_Room',
		runtimeType: 'CollectableRelic',
		rewardAmount: 90,
		typeNameKey: 'UI.INV_NAME_R_BONE_RECORD',
		typeDescriptionKey: 'UI.INV_DESC_R_BONE_RECORD',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0002_R_bone_record_11_123x142_1',
			nameShort: 'Hornet_icon_0002_R_bone_record',
			size: {
				x: 123,
				y: 142,
			},
			padding: {
				x: 2.026751,
				y: 2.07612038,
				z: 2.04290771,
				w: 2.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0002_R_bone_record_11_123x142_1',
			nameShort: 'Hornet_icon_0002_R_bone_record',
			size: {
				x: 123,
				y: 142,
			},
			padding: {
				x: 2.026751,
				y: 2.07612038,
				z: 2.04290771,
				w: 2.02674866,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Bone Record',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0002_R_bone_record_11_123x142_1',
			nameShort: 'Hornet_icon_0002_R_bone_record',
			size: {
				x: 123,
				y: 142,
			},
			padding: {
				x: 2.026751,
				y: 2.07612038,
				z: 2.04290771,
				w: 2.02674866,
			},
		},
	},
	{
		id: 'Bone Record Wisp Top',
		runtimeType: 'CollectableRelic',
		rewardAmount: 90,
		typeNameKey: 'UI.INV_NAME_R_BONE_RECORD',
		typeDescriptionKey: 'UI.INV_DESC_R_BONE_RECORD',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0002_R_bone_record_11_123x142_1',
			nameShort: 'Hornet_icon_0002_R_bone_record',
			size: {
				x: 123,
				y: 142,
			},
			padding: {
				x: 2.026751,
				y: 2.07612038,
				z: 2.04290771,
				w: 2.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0002_R_bone_record_11_123x142_1',
			nameShort: 'Hornet_icon_0002_R_bone_record',
			size: {
				x: 123,
				y: 142,
			},
			padding: {
				x: 2.026751,
				y: 2.07612038,
				z: 2.04290771,
				w: 2.02674866,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Bone Record',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0002_R_bone_record_11_123x142_1',
			nameShort: 'Hornet_icon_0002_R_bone_record',
			size: {
				x: 123,
				y: 142,
			},
			padding: {
				x: 2.026751,
				y: 2.07612038,
				z: 2.04290771,
				w: 2.02674866,
			},
		},
	},
	{
		id: 'Seal Chit Aspid_01',
		runtimeType: 'CollectableRelic',
		rewardAmount: 180,
		typeNameKey: 'UI.INV_NAME_R_SEAL_CHIT',
		typeDescriptionKey: 'UI.INV_DESC_R_SEAL_CHIT',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0000_R_seal_chit_7_119x158_1',
			nameShort: 'Hornet_icon_0000_R_seal_chit',
			size: {
				x: 119,
				y: 158,
			},
			padding: {
				x: 0.0761204958,
				y: 0.0761204958,
				z: 2.012909,
				w: 1.0761261,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0000_R_seal_chit_7_119x158_1',
			nameShort: 'Hornet_icon_0000_R_seal_chit',
			size: {
				x: 119,
				y: 158,
			},
			padding: {
				x: 0.0761204958,
				y: 0.0761204958,
				z: 2.012909,
				w: 1.0761261,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Seal Chit',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0000_R_seal_chit_7_119x158_1',
			nameShort: 'Hornet_icon_0000_R_seal_chit',
			size: {
				x: 119,
				y: 158,
			},
			padding: {
				x: 0.0761204958,
				y: 0.0761204958,
				z: 2.012909,
				w: 1.0761261,
			},
		},
	},
	{
		id: 'Seal Chit Ward Corpse',
		runtimeType: 'CollectableRelic',
		rewardAmount: 180,
		typeNameKey: 'UI.INV_NAME_R_SEAL_CHIT',
		typeDescriptionKey: 'UI.INV_DESC_R_SEAL_CHIT',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0000_R_seal_chit_7_119x158_1',
			nameShort: 'Hornet_icon_0000_R_seal_chit',
			size: {
				x: 119,
				y: 158,
			},
			padding: {
				x: 0.0761204958,
				y: 0.0761204958,
				z: 2.012909,
				w: 1.0761261,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0000_R_seal_chit_7_119x158_1',
			nameShort: 'Hornet_icon_0000_R_seal_chit',
			size: {
				x: 119,
				y: 158,
			},
			padding: {
				x: 0.0761204958,
				y: 0.0761204958,
				z: 2.012909,
				w: 1.0761261,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Seal Chit',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0000_R_seal_chit_7_119x158_1',
			nameShort: 'Hornet_icon_0000_R_seal_chit',
			size: {
				x: 119,
				y: 158,
			},
			padding: {
				x: 0.0761204958,
				y: 0.0761204958,
				z: 2.012909,
				w: 1.0761261,
			},
		},
	},
	{
		id: 'Seal Chit City Merchant',
		runtimeType: 'CollectableRelic',
		rewardAmount: 180,
		typeNameKey: 'UI.INV_NAME_R_SEAL_CHIT',
		typeDescriptionKey: 'UI.INV_DESC_R_SEAL_CHIT',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0000_R_seal_chit_7_119x158_1',
			nameShort: 'Hornet_icon_0000_R_seal_chit',
			size: {
				x: 119,
				y: 158,
			},
			padding: {
				x: 0.0761204958,
				y: 0.0761204958,
				z: 2.012909,
				w: 1.0761261,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0000_R_seal_chit_7_119x158_1',
			nameShort: 'Hornet_icon_0000_R_seal_chit',
			size: {
				x: 119,
				y: 158,
			},
			padding: {
				x: 0.0761204958,
				y: 0.0761204958,
				z: 2.012909,
				w: 1.0761261,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Seal Chit',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0000_R_seal_chit_7_119x158_1',
			nameShort: 'Hornet_icon_0000_R_seal_chit',
			size: {
				x: 119,
				y: 158,
			},
			padding: {
				x: 0.0761204958,
				y: 0.0761204958,
				z: 2.012909,
				w: 1.0761261,
			},
		},
	},
	{
		id: 'Seal Chit Silk Siphon',
		runtimeType: 'CollectableRelic',
		rewardAmount: 180,
		typeNameKey: 'UI.INV_NAME_R_SEAL_CHIT',
		typeDescriptionKey: 'UI.INV_DESC_R_SEAL_CHIT',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0000_R_seal_chit_7_119x158_1',
			nameShort: 'Hornet_icon_0000_R_seal_chit',
			size: {
				x: 119,
				y: 158,
			},
			padding: {
				x: 0.0761204958,
				y: 0.0761204958,
				z: 2.012909,
				w: 1.0761261,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0000_R_seal_chit_7_119x158_1',
			nameShort: 'Hornet_icon_0000_R_seal_chit',
			size: {
				x: 119,
				y: 158,
			},
			padding: {
				x: 0.0761204958,
				y: 0.0761204958,
				z: 2.012909,
				w: 1.0761261,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Seal Chit',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0000_R_seal_chit_7_119x158_1',
			nameShort: 'Hornet_icon_0000_R_seal_chit',
			size: {
				x: 119,
				y: 158,
			},
			padding: {
				x: 0.0761204958,
				y: 0.0761204958,
				z: 2.012909,
				w: 1.0761261,
			},
		},
	},
	{
		id: 'Weaver Totem Bonetown_upper_room',
		runtimeType: 'CollectableRelic',
		rewardAmount: 150,
		typeNameKey: 'UI.INV_NAME_R_WEAVER_TOTEM',
		typeDescriptionKey: 'UI.INV_DESC_R_WEAVER_TOTEM',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0005_R_saint_locket_9_114x157_1',
			nameShort: 'Hornet_icon_0005_R_saint_locket',
			size: {
				x: 114,
				y: 157,
			},
			padding: {
				x: 6.07612038,
				y: 3.026751,
				z: 15.0513153,
				w: 3.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0005_R_saint_locket_9_114x157_1',
			nameShort: 'Hornet_icon_0005_R_saint_locket',
			size: {
				x: 114,
				y: 157,
			},
			padding: {
				x: 6.07612038,
				y: 3.026751,
				z: 15.0513153,
				w: 3.02674866,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Weaver Totem',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0005_R_saint_locket_9_114x157_1',
			nameShort: 'Hornet_icon_0005_R_saint_locket',
			size: {
				x: 114,
				y: 157,
			},
			padding: {
				x: 6.07612038,
				y: 3.026751,
				z: 15.0513153,
				w: 3.02674866,
			},
		},
	},
	{
		id: 'Weaver Totem Witch',
		runtimeType: 'CollectableRelic',
		rewardAmount: 150,
		typeNameKey: 'UI.INV_NAME_R_WEAVER_TOTEM',
		typeDescriptionKey: 'UI.INV_DESC_R_WEAVER_TOTEM',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0005_R_saint_locket_9_114x157_1',
			nameShort: 'Hornet_icon_0005_R_saint_locket',
			size: {
				x: 114,
				y: 157,
			},
			padding: {
				x: 6.07612038,
				y: 3.026751,
				z: 15.0513153,
				w: 3.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0005_R_saint_locket_9_114x157_1',
			nameShort: 'Hornet_icon_0005_R_saint_locket',
			size: {
				x: 114,
				y: 157,
			},
			padding: {
				x: 6.07612038,
				y: 3.026751,
				z: 15.0513153,
				w: 3.02674866,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Weaver Totem',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0005_R_saint_locket_9_114x157_1',
			nameShort: 'Hornet_icon_0005_R_saint_locket',
			size: {
				x: 114,
				y: 157,
			},
			padding: {
				x: 6.07612038,
				y: 3.026751,
				z: 15.0513153,
				w: 3.02674866,
			},
		},
	},
	{
		id: 'Weaver Totem Slab_Bottom',
		runtimeType: 'CollectableRelic',
		rewardAmount: 150,
		typeNameKey: 'UI.INV_NAME_R_WEAVER_TOTEM',
		typeDescriptionKey: 'UI.INV_DESC_R_WEAVER_TOTEM',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0005_R_saint_locket_9_114x157_1',
			nameShort: 'Hornet_icon_0005_R_saint_locket',
			size: {
				x: 114,
				y: 157,
			},
			padding: {
				x: 6.07612038,
				y: 3.026751,
				z: 15.0513153,
				w: 3.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0005_R_saint_locket_9_114x157_1',
			nameShort: 'Hornet_icon_0005_R_saint_locket',
			size: {
				x: 114,
				y: 157,
			},
			padding: {
				x: 6.07612038,
				y: 3.026751,
				z: 15.0513153,
				w: 3.02674866,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Weaver Totem',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0005_R_saint_locket_9_114x157_1',
			nameShort: 'Hornet_icon_0005_R_saint_locket',
			size: {
				x: 114,
				y: 157,
			},
			padding: {
				x: 6.07612038,
				y: 3.026751,
				z: 15.0513153,
				w: 3.02674866,
			},
		},
	},
	{
		id: 'Weaver Record Weave_08',
		runtimeType: 'CollectableRelic',
		rewardAmount: 210,
		typeNameKey: 'UI.INV_NAME_R_WEAVER_RECORD',
		typeDescriptionKey: 'UI.INV_DESC_R_WEAVER_RECORD',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0002_R_weaver_record_9_109x164_4',
			nameShort: 'Hornet_icon_0002_R_weaver_record',
			size: {
				x: 109,
				y: 164,
			},
			padding: {
				x: 6.07612038,
				y: 4.036285,
				z: 7.05131531,
				w: 4.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0002_R_weaver_record_9_109x164_4',
			nameShort: 'Hornet_icon_0002_R_weaver_record',
			size: {
				x: 109,
				y: 164,
			},
			padding: {
				x: 6.07612038,
				y: 4.036285,
				z: 7.05131531,
				w: 4.02674866,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Weaver Record',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0002_R_weaver_record_9_109x164_4',
			nameShort: 'Hornet_icon_0002_R_weaver_record',
			size: {
				x: 109,
				y: 164,
			},
			padding: {
				x: 6.07612038,
				y: 4.036285,
				z: 7.05131531,
				w: 4.02674866,
			},
		},
	},
	{
		id: 'Weaver Record Sprint_Challenge',
		runtimeType: 'CollectableRelic',
		rewardAmount: 210,
		typeNameKey: 'UI.INV_NAME_R_WEAVER_RECORD',
		typeDescriptionKey: 'UI.INV_DESC_R_WEAVER_RECORD',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0002_R_weaver_record_9_109x164_4',
			nameShort: 'Hornet_icon_0002_R_weaver_record',
			size: {
				x: 109,
				y: 164,
			},
			padding: {
				x: 6.07612038,
				y: 4.036285,
				z: 7.05131531,
				w: 4.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0002_R_weaver_record_9_109x164_4',
			nameShort: 'Hornet_icon_0002_R_weaver_record',
			size: {
				x: 109,
				y: 164,
			},
			padding: {
				x: 6.07612038,
				y: 4.036285,
				z: 7.05131531,
				w: 4.02674866,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Weaver Record',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0002_R_weaver_record_9_109x164_4',
			nameShort: 'Hornet_icon_0002_R_weaver_record',
			size: {
				x: 109,
				y: 164,
			},
			padding: {
				x: 6.07612038,
				y: 4.036285,
				z: 7.05131531,
				w: 4.02674866,
			},
		},
	},
	{
		id: 'Weaver Record Conductor',
		runtimeType: 'CollectableRelic',
		rewardAmount: 210,
		typeNameKey: 'UI.INV_NAME_R_WEAVER_RECORD',
		typeDescriptionKey: 'UI.INV_DESC_R_WEAVER_RECORD',
		appendDescriptionKey: 'UI.INV_DESC_RELIC',
		collectionIcon: {
			name: 'Hornet_icon_0002_R_weaver_record_9_109x164_4',
			nameShort: 'Hornet_icon_0002_R_weaver_record',
			size: {
				x: 109,
				y: 164,
			},
			padding: {
				x: 6.07612038,
				y: 4.036285,
				z: 7.05131531,
				w: 4.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0002_R_weaver_record_9_109x164_4',
			nameShort: 'Hornet_icon_0002_R_weaver_record',
			size: {
				x: 109,
				y: 164,
			},
			padding: {
				x: 6.07612038,
				y: 4.036285,
				z: 7.05131531,
				w: 4.02674866,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Weaver Record',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0002_R_weaver_record_9_109x164_4',
			nameShort: 'Hornet_icon_0002_R_weaver_record',
			size: {
				x: 109,
				y: 164,
			},
			padding: {
				x: 6.07612038,
				y: 4.036285,
				z: 7.05131531,
				w: 4.02674866,
			},
		},
	},
	{
		id: 'Ancient Egg Abyss Middle',
		runtimeType: 'CollectableRelic',
		rewardAmount: 600,
		typeNameKey: 'UI.INV_NAME_R_ANCIENT_EGG',
		typeDescriptionKey: 'UI.INV_DESC_R_ANCIENT_EGG',
		appendDescriptionKey: null,
		collectionIcon: {
			name: 'Hornet_icon_0004_R_ancient_egg_9_104x103_1',
			nameShort: 'Hornet_icon_0004_R_ancient_egg',
			size: {
				x: 104,
				y: 103,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0004_R_ancient_egg_9_104x103_1',
			nameShort: 'Hornet_icon_0004_R_ancient_egg',
			size: {
				x: 104,
				y: 103,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		isInInventory: false,
		isPlayable: false,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Ancient Egg',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0004_R_ancient_egg_9_104x103_1',
			nameShort: 'Hornet_icon_0004_R_ancient_egg',
			size: {
				x: 104,
				y: 103,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
	},
	{
		id: 'Psalm Cylinder Librarian',
		runtimeType: 'CollectableRelic',
		rewardAmount: 200,
		typeNameKey: 'UI.INV_NAME_R_PSALM_CYL',
		typeDescriptionKey: 'UI.INV_DESC_R_PSALM_CYL',
		appendDescriptionKey: null,
		collectionIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
		isInInventory: false,
		isPlayable: true,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Psalm Cylinder',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
	},
	{
		id: 'Psalm Cylinder Library Roof',
		runtimeType: 'CollectableRelic',
		rewardAmount: 200,
		typeNameKey: 'UI.INV_NAME_R_PSALM_CYL',
		typeDescriptionKey: 'UI.INV_DESC_R_PSALM_CYL',
		appendDescriptionKey: null,
		collectionIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
		isInInventory: false,
		isPlayable: true,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Psalm Cylinder',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
	},
	{
		id: 'Psalm Cylinder Ward',
		runtimeType: 'CollectableRelic',
		rewardAmount: 200,
		typeNameKey: 'UI.INV_NAME_R_PSALM_CYL',
		typeDescriptionKey: 'UI.INV_DESC_R_PSALM_CYL',
		appendDescriptionKey: null,
		collectionIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
		isInInventory: false,
		isPlayable: true,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Psalm Cylinder',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
	},
	{
		id: 'Psalm Cylinder Grindle',
		runtimeType: 'CollectableRelic',
		rewardAmount: 200,
		typeNameKey: 'UI.INV_NAME_R_PSALM_CYL',
		typeDescriptionKey: 'UI.INV_DESC_R_PSALM_CYL',
		appendDescriptionKey: null,
		collectionIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
		isInInventory: false,
		isPlayable: true,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Psalm Cylinder',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
	},
	{
		id: 'Psalm Cylinder Hang',
		runtimeType: 'CollectableRelic',
		rewardAmount: 200,
		typeNameKey: 'UI.INV_NAME_R_PSALM_CYL',
		typeDescriptionKey: 'UI.INV_DESC_R_PSALM_CYL',
		appendDescriptionKey: null,
		collectionIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
		isInInventory: false,
		isPlayable: true,
		playSyncedAudioSource: false,
		willSendPlayEvent: false,
		relicTypeId: 'R Psalm Cylinder',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_10_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.026749,
				w: 5.02674866,
			},
		},
	},
	{
		id: 'Librarian Melody Cylinder',
		runtimeType: 'CollectableRelic',
		rewardAmount: 320,
		typeNameKey: 'UI.INV_NAME_R_PSALM_CYL_MELODY',
		typeDescriptionKey: 'UI.INV_DESC_R_PSALM_CYL_MELODY',
		appendDescriptionKey: null,
		collectionIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_white_9_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder_white',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.076118,
				w: 5.02674866,
			},
		},
		popupIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_white_9_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder_white',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.076118,
				w: 5.02674866,
			},
		},
		isInInventory: false,
		isPlayable: true,
		playSyncedAudioSource: true,
		willSendPlayEvent: false,
		relicTypeId: 'R Librarian Melody Cylinder',
		relicTypeInventoryIcon: {
			name: 'Hornet_icon_0000_R_psalm_cylinder_white_9_135x135_1',
			nameShort: 'Hornet_icon_0000_R_psalm_cylinder_white',
			size: {
				x: 135,
				y: 135,
			},
			padding: {
				x: 4.026751,
				y: 5.026751,
				z: 8.076118,
				w: 5.02674866,
			},
		},
	},
];
export type CollectableRelicSilk = (typeof list)[number];
export const collectableRelicSilk = {
	list,
	byName: Object.fromEntries(list.map((it: any) => [it.id, it])) as Record<
		CollectableRelicNameSilk,
		CollectableRelicSilk
	>,
};

export const collectableRelicIdToNameSilk: Map<number, CollectableRelicNameSilk> = new Map([
	[1, 'Bone Record Greymoor_flooded_corridor'],
	[2, 'Bone Record Bone_East_14'],
	[3, 'Bone Record Understore_Map_Room'],
	[4, 'Bone Record Wisp Top'],
	[5, 'Seal Chit Aspid_01'],
	[6, 'Seal Chit Ward Corpse'],
	[7, 'Seal Chit City Merchant'],
	[8, 'Seal Chit Silk Siphon'],
	[9, 'Weaver Totem Bonetown_upper_room'],
	[10, 'Weaver Totem Witch'],
	[11, 'Weaver Totem Slab_Bottom'],
	[12, 'Weaver Record Weave_08'],
	[13, 'Weaver Record Sprint_Challenge'],
	[14, 'Weaver Record Conductor'],
	[15, 'Ancient Egg Abyss Middle'],
	[16, 'Psalm Cylinder Librarian'],
	[17, 'Psalm Cylinder Library Roof'],
	[18, 'Psalm Cylinder Ward'],
	[19, 'Psalm Cylinder Grindle'],
	[20, 'Psalm Cylinder Hang'],
	[21, 'Librarian Melody Cylinder'],
]);
export const collectableRelicNamesSilk: CollectableRelicNameSilk[] = collectableRelicIdToNameSilk.values().toArray();
