/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */

export type ExtraToolSlotNameSilk = 'Defend1' | 'Explore1';

const list = [
	{
		id: 'Defend1',
	},
	{
		id: 'Explore1',
	},
];
export type ExtraToolSlotSilk = (typeof list)[number];
export const extraToolSlotSilk = {
	list,
	byName: Object.fromEntries(list.map((it: any) => [it.id, it])) as Record<ExtraToolSlotNameSilk, ExtraToolSlotSilk>,
};

export const extraToolSlotIdToNameSilk: Map<number, ExtraToolSlotNameSilk> = new Map([
	[1, 'Defend1'],
	[2, 'Explore1'],
]);
export const extraToolSlotNamesSilk: ExtraToolSlotNameSilk[] = extraToolSlotIdToNameSilk.values().toArray();
