/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
export const extraToolSlotSilk = { all: [{ id: 'Defend1' }, { id: 'Explore1' }] };
export type ExtraToolSlotNameSilk = 'Defend1' | 'Explore1';

export const extraToolSlotIdToNameSilk: Map<number, ExtraToolSlotNameSilk> = new Map([
	[1, 'Defend1'],
	[2, 'Explore1'],
]);
export const extraToolSlotNamesSilk: ExtraToolSlotNameSilk[] = extraToolSlotIdToNameSilk.values().toArray();
