/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */

export type MateriumNameSilk =
	| 'Silk'
	| 'Shell Shard'
	| 'Rosary Small'
	| 'Rosary Mid'
	| 'Rosary Big'
	| 'Mossberry'
	| 'Mossberry Stew'
	| 'Pilgrim Rag'
	| 'Smeltstone'
	| 'Rock Roller Item'
	| 'Tool Metal'
	| 'Common Spine'
	| 'Skull King Fragment'
	| 'Beastfly Remains'
	| 'Silver Bellclapper'
	| 'Pale Oil'
	| 'Lifeblood'
	| 'Plasmium Blood'
	| 'Crow Feathers'
	| 'Shell Flower'
	| 'Roach Corpse Item'
	| 'Courier Supplies Generic'
	| 'Courier Supplies Slave'
	| 'Courier Supplies Mask Maker'
	| 'Courier Supplies Gourmand'
	| 'Vintage Nectar'
	| 'Pickled Roach Egg'
	| 'Crustnut'
	| 'Extractor Machine Pins'
	| 'Song Pilgrim Cloak'
	| 'Magnetite'
	| 'Broodmother Remains'
	| 'Enemy Morsel Seared'
	| 'Enemy Morsel Shredded'
	| 'Enemy Morsel Speared'
	| 'Voltstone'
	| 'Snare Soul Bell Hermit'
	| 'Snare Soul Churchkeeper'
	| 'Snare Soul Swamp Bug'
	| 'Flower Heart'
	| 'Hunter Heart'
	| 'Coral Heart'
	| 'Clover Heart';

const list = [
	{
		id: 'Silk',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.MAT_NAME_SILK',
		descriptionKey: 'UI.MAT_DESC_SILK',
		icon: {
			name: 'icon_silk_materium_13_134x151_4',
			nameShort: 'icon_silk_materium',
			size: {
				x: 134,
				y: 151,
			},
			padding: {
				x: 6.04290771,
				y: 20.02675,
				z: 11.0129089,
				w: 20.0597229,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Shell Shard',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_SHARD',
		descriptionKey: 'UI.INV_DESC_SHARD',
		icon: {
			name: 'I_shell_shard_icon_large_9_120x119_1',
			nameShort: 'I_shell_shard_icon_large',
			size: {
				x: 120,
				y: 119,
			},
			padding: {
				x: 2.07612038,
				y: 9.07612,
				z: 0,
				w: 9.076118,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Rosary Small',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_COIN',
		descriptionKey: 'UI.INV_DESC_COIN',
		icon: {
			name: 'I_rosary_icon_clean_9_119x119_1',
			nameShort: 'I_rosary_icon_clean',
			size: {
				x: 119,
				y: 119,
			},
			padding: {
				x: 3.07612038,
				y: 2.026751,
				z: 5.02674866,
				w: 3.02674866,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Rosary Mid',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_COIN_MID',
		descriptionKey: 'UI.INV_DESC_COIN_MID',
		icon: {
			name: 'I_rosary_icon_mid_clean_9_120x119_1',
			nameShort: 'I_rosary_icon_mid_clean',
			size: {
				x: 120,
				y: 119,
			},
			padding: {
				x: 0.0761204958,
				y: 8.026751,
				z: 1.02674866,
				w: 8.076118,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Rosary Big',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_COIN_BIG',
		descriptionKey: 'UI.INV_DESC_COIN_BIG',
		icon: {
			name: 'I_rosary_icon_big_clean_9_120x119_1',
			nameShort: 'I_rosary_icon_big_clean',
			size: {
				x: 120,
				y: 119,
			},
			padding: {
				x: 5.07612038,
				y: 2.05820465,
				z: 1.0362854,
				w: 3.02674866,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Mossberry',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_MOSSBERRY',
		descriptionKey: 'UI.INV_DESC_MOSSBERRY',
		icon: {
			name: 'I_moss_berry_12_120x120_0',
			nameShort: 'I_moss_berry',
			size: {
				x: 120,
				y: 120,
			},
			padding: {
				x: 7.07612038,
				y: 6.07612038,
				z: 11.0761185,
				w: 1.05131531,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Mossberry Stew',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_GOURMAND_MOSSBERRY_STEW',
		descriptionKey: 'UI.INV_DESC_GOURMAND_MOSSBERRY_STEW',
		icon: {
			name: 'Mossberry_Stew_9_125x128_1',
			nameShort: 'Mossberry_Stew',
			size: {
				x: 125,
				y: 128,
			},
			padding: {
				x: 3.026751,
				y: 4.07612038,
				z: 3.07611847,
				w: 2.04290771,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Pilgrim Rag',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_PILGRIM_RAGS_ITEM',
		descriptionKey: 'UI.INV_DESC_PILGRIM_RAGS_ITEM',
		icon: {
			name: 'Hornet_icon_pilgrim_shawl_10_130x112_1',
			nameShort: 'Hornet_icon_pilgrim_shawl',
			size: {
				x: 130,
				y: 112,
			},
			padding: {
				x: 0.0267509818,
				y: 0,
				z: 2.02674866,
				w: 2.07611847,
			},
		},
		isRequiredForCompletion: false,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Smeltstone',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.MAT_NAME_SMELTSTONE',
		descriptionKey: 'UI.MAT_DESC_SMELTSTONE',
		icon: {
			name: 'Smeltstone_icon_9_128x143_1',
			nameShort: 'Smeltstone_icon',
			size: {
				x: 128,
				y: 143,
			},
			padding: {
				x: 4.07612038,
				y: 11.0267506,
				z: 6.05131531,
				w: 9.011124,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Rock Roller Item',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_ROCK_ROLLER_ITEM',
		descriptionKey: 'UI.INV_DESC_ROCK_ROLLER_ITEM',
		icon: {
			name: 'bone_roller_rock_icon_9_132x117_0',
			nameShort: 'bone_roller_rock_icon',
			size: {
				x: 132,
				y: 117,
			},
			padding: {
				x: 9.026751,
				y: 2.07612038,
				z: 10.0267487,
				w: 2.03350067,
			},
		},
		isRequiredForCompletion: false,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Tool Metal',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_TOOL_METAL',
		descriptionKey: 'UI.INV_DESC_TOOL_METAL',
		icon: {
			name: 'Hornet_Tool_Metal_10_110x117_0',
			nameShort: 'Hornet_Tool_Metal',
			size: {
				x: 110,
				y: 117,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Common Spine',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_SPINE',
		descriptionKey: 'UI.INV_DESC_SPINE',
		icon: {
			name: 'Hornet_spine_cores_13_142x145_0',
			nameShort: 'Hornet_spine_cores',
			size: {
				x: 142,
				y: 145,
			},
			padding: {
				x: 21.02675,
				y: 7.026751,
				z: 15.0429077,
				w: 0,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Skull King Fragment',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_SK_FRAGMENT',
		descriptionKey: 'UI.INV_DESC_SK_FRAGMENT',
		icon: {
			name: 'M_tusk_9_120x120_1',
			nameShort: 'M_tusk',
			size: {
				x: 120,
				y: 120,
			},
			padding: {
				x: 5.07612038,
				y: 7.07612038,
				z: 5.05131531,
				w: 7.02674866,
			},
		},
		isRequiredForCompletion: false,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Beastfly Remains',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_BEASTFLY_REMAINS',
		descriptionKey: 'UI.INV_DESC_BEASTFLY_REMAINS',
		icon: {
			name: 'M_crest_8_120x120_1',
			nameShort: 'M_crest',
			size: {
				x: 120,
				y: 120,
			},
			padding: {
				x: 7.04290771,
				y: 0.0267509818,
				z: 5.02674866,
				w: 1.02674866,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Silver Bellclapper',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_BELLCLAPPER_ITEM',
		descriptionKey: 'UI.INV_DESC_BELLCLAPPER_ITEM',
		icon: {
			name: 'Hornet_icon_bell_clapper_8_144x157_2',
			nameShort: 'Hornet_icon_bell_clapper',
			size: {
				x: 144,
				y: 157,
			},
			padding: {
				x: 16.0597286,
				y: 13.07612,
				z: 24.0761185,
				w: 13.0429077,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Pale Oil',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_PLINNEY_TOOLS',
		descriptionKey: 'UI.INV_DESC_PLINNEY_TOOLS',
		icon: {
			name: 'oil_phial_8_111x125_1',
			nameShort: 'oil_phial',
			size: {
				x: 111,
				y: 125,
			},
			padding: {
				x: 0.0761204958,
				y: 1.0761205,
				z: 1.07611847,
				w: 1.04290771,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Lifeblood',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.MAT_NAME_LIFEBLOOD',
		descriptionKey: 'UI.MAT_DESC_LIFEBLOOD',
		icon: {
			name: 'Icon_Inv_Blue_Health_Jar_0001_3_7_116x120_1',
			nameShort: 'Icon_Inv_Blue_Health_Jar_0001_3',
			size: {
				x: 116,
				y: 120,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Plasmium Blood',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_PLASMIUM_BLOOD',
		descriptionKey: 'UI.INV_DESC_PLASMIUM_BLOOD',
		icon: {
			name: 'Icon_Inv_Blue_Health_Blood_7_138x164_1',
			nameShort: 'Icon_Inv_Blue_Health_Blood',
			size: {
				x: 138,
				y: 164,
			},
			padding: {
				x: 9.042908,
				y: 6.026751,
				z: 14.0761185,
				w: 7.01005554,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Crow Feathers',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_CROW_FEATHER',
		descriptionKey: 'UI.INV_DESC_CROW_FEATHER',
		icon: {
			name: 'Hornet_craw_scrap_11_142x145_0',
			nameShort: 'Hornet_craw_scrap',
			size: {
				x: 142,
				y: 145,
			},
			padding: {
				x: 15.0267506,
				y: 1.026751,
				z: 4.076126,
				w: 1.0597229,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Shell Flower',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_SHELL_FLOWER',
		descriptionKey: 'UI.INV_DESC_SHELL_FLOWER',
		icon: {
			name: '_0007_shell_flower_purple_icon_9_76x115_0',
			nameShort: '_0007_shell_flower_purple_icon',
			size: {
				x: 76,
				y: 115,
			},
			padding: {
				x: 1.026751,
				y: 1.036285,
				z: 2.012909,
				w: 0.07611847,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Roach Corpse Item',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_ROACH_CORPSE_ITEM',
		descriptionKey: 'UI.INV_DESC_ROACH_CORPSE_ITEM',
		icon: {
			name: 'icon_roach_organ_11_119x128_2',
			nameShort: 'icon_roach_organ',
			size: {
				x: 119,
				y: 128,
			},
			padding: {
				x: 0.0267509818,
				y: 2.07612038,
				z: 2.02674866,
				w: 3.02674866,
			},
		},
		isRequiredForCompletion: false,
		isCollected: false,
		isSeen: false,
		isVisibleInCollection: false,
	},
	{
		id: 'Courier Supplies Generic',
		runtimeType: 'MateriumItem',
		displayNameKey: 'Quests.COURIER_SUPPLIES_ITEM_NAME',
		descriptionKey: 'Quests.COURIER_SUPPLIES_ITEM_DESC',
		icon: {
			name: 'Icon_Courier_Supplies_9_133x130_1',
			nameShort: 'Icon_Courier_Supplies',
			size: {
				x: 133,
				y: 130,
			},
			padding: {
				x: 7.07612038,
				y: 2.026751,
				z: 8.076118,
				w: 5.07611847,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Courier Supplies Slave',
		runtimeType: 'MateriumItem',
		displayNameKey: 'Quests.COURIER_SUPPLIES_SLAVE_NAME',
		descriptionKey: 'Quests.COURIER_SUPPLIES_SLAVE_DESC',
		icon: {
			name: 'Hornet_Item_Egg_13_112x107_1',
			nameShort: 'Hornet_Item_Egg',
			size: {
				x: 112,
				y: 107,
			},
			padding: {
				x: 2.026751,
				y: 0,
				z: 1.02674866,
				w: 0,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Courier Supplies Mask Maker',
		runtimeType: 'MateriumItem',
		displayNameKey: 'Quests.COURIER_SUPPLIES_MASK_NAME',
		descriptionKey: 'Quests.COURIER_SUPPLIES_MASK_DESC',
		icon: {
			name: 'Icon_Courier_Supplies_Lacquer_8_134x130_1',
			nameShort: 'Icon_Courier_Supplies_Lacquer',
			size: {
				x: 134,
				y: 130,
			},
			padding: {
				x: 3.07612038,
				y: 0.0761204958,
				z: 5.02674866,
				w: 0,
			},
		},
		isRequiredForCompletion: true,
		isCollected: false,
		isSeen: false,
		isVisibleInCollection: false,
	},
	{
		id: 'Courier Supplies Gourmand',
		runtimeType: 'MateriumItem',
		displayNameKey: 'Quests.COURIER_SUPPLIES_MEAT_NAME',
		descriptionKey: 'Quests.COURIER_SUPPLIES_MEAT_DESC',
		icon: {
			name: 'Icon_Courier_Supplies_Meat_Sack_7_116x123_1',
			nameShort: 'Icon_Courier_Supplies_Meat_Sack',
			size: {
				x: 116,
				y: 123,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Vintage Nectar',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_GOURMAND_VINTAGE_NECTAR',
		descriptionKey: 'UI.INV_DESC_GOURMAND_VINTAGE_NECTAR',
		icon: {
			name: 'vintage_nectar_item_9_137x140_1',
			nameShort: 'vintage_nectar_item',
			size: {
				x: 137,
				y: 140,
			},
			padding: {
				x: 6.07612038,
				y: 3.07612038,
				z: 9.064629,
				w: 7.02674866,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Pickled Roach Egg',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_PICKLEDEGG',
		descriptionKey: 'UI.INV_DESC_PICKLEDEGG',
		icon: {
			name: 'century_maggot_icon_10_130x129_1',
			nameShort: 'century_maggot_icon',
			size: {
				x: 130,
				y: 129,
			},
			padding: {
				x: 0.0761204958,
				y: 7.01291275,
				z: 2.07611847,
				w: 4.02674866,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Crustnut',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_GOURMAND_CORAL_INGREDIENT',
		descriptionKey: 'UI.INV_DESC_GOURMAND_CORAL_INGREDIENT',
		icon: {
			name: '_0007_quest_coral_nut_15_115x129_1',
			nameShort: '_0007_quest_coral_nut',
			size: {
				x: 115,
				y: 129,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Extractor Machine Pins',
		runtimeType: 'MateriumItem',
		displayNameKey: 'Quests.ITEM_EXTRACTOR_PINS_NAME',
		descriptionKey: 'Quests.ITEM_EXTRACTOR_PINS_DESC',
		icon: {
			name: 'Hornet_Extractor_Pins_9_125x154_1',
			nameShort: 'Hornet_Extractor_Pins',
			size: {
				x: 125,
				y: 154,
			},
			padding: {
				x: 1.026751,
				y: 1.01680481,
				z: 1.07611847,
				w: 1.05131531,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Song Pilgrim Cloak',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_SONGPILGRIM_CLOAK_ITEM',
		descriptionKey: 'UI.INV_DESC_SONGPILGRIM_CLOAK_ITEM',
		icon: {
			name: 'icon_song_shawl_10_120x117_1',
			nameShort: 'icon_song_shawl',
			size: {
				x: 120,
				y: 117,
			},
			padding: {
				x: 0.0761204958,
				y: 0.05131668,
				z: 0.0129089355,
				w: 0.07611847,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Magnetite',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.MAT_NAME_MAGNETITE',
		descriptionKey: 'UI.MAT_DESC_MAGNETITE',
		icon: {
			name: 'icon_magnetite_8_131x142_2',
			nameShort: 'icon_magnetite',
			size: {
				x: 131,
				y: 142,
			},
			padding: {
				x: 3.026751,
				y: 1.026751,
				z: 7.02674866,
				w: 3.076126,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Broodmother Remains',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_BROODMOTHER_REMAINS',
		descriptionKey: 'UI.INV_DESC_BROODMOTHER_REMAINS',
		icon: {
			name: 'Brood_Mother_Eye_Icon_9_125x146_2',
			nameShort: 'Brood_Mother_Eye_Icon',
			size: {
				x: 125,
				y: 146,
			},
			padding: {
				x: 3.01291251,
				y: 1.0761205,
				z: 7.012909,
				w: 0,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Enemy Morsel Seared',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_MORSEL_SEARED',
		descriptionKey: 'UI.INV_DESC_MORSEL_SEARED',
		icon: {
			name: 'icon_meat_seared_9_132x126_1',
			nameShort: 'icon_meat_seared',
			size: {
				x: 132,
				y: 126,
			},
			padding: {
				x: 9.026751,
				y: 7.026751,
				z: 10.0267487,
				w: 6.04290771,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Enemy Morsel Shredded',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_MORSEL_SHREDDED',
		descriptionKey: 'UI.INV_DESC_MORSEL_SHREDDED',
		icon: {
			name: 'icon_meat_sliced_14_122x126_2',
			nameShort: 'icon_meat_sliced',
			size: {
				x: 122,
				y: 126,
			},
			padding: {
				x: 8.07612,
				y: 3.07612038,
				z: 9.026749,
				w: 1.02674866,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Enemy Morsel Speared',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_MORSEL_SPEARED',
		descriptionKey: 'UI.INV_DESC_MORSEL_SPEARED',
		icon: {
			name: 'icon_meat_skewered_8_172x157_2',
			nameShort: 'icon_meat_skewered',
			size: {
				x: 172,
				y: 157,
			},
			padding: {
				x: 25.07612,
				y: 20.0429077,
				z: 26.0761261,
				w: 25.0761261,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Voltstone',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.MAT_NAME_VOLTSTONE',
		descriptionKey: 'UI.MAT_DESC_VOLTSTONE',
		icon: {
			name: 'icon_lightning_rock_8_132x143_1',
			nameShort: 'icon_lightning_rock',
			size: {
				x: 132,
				y: 143,
			},
			padding: {
				x: 11.0267506,
				y: 13.0429077,
				z: 7.05973053,
				w: 14.0761261,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Snare Soul Bell Hermit',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_SNARE_SOUL_BELLHERMIT',
		descriptionKey: 'UI.INV_DESC_SNARE_SOUL_BELLHERMIT',
		icon: {
			name: 'snail_icon__0001_bell_hermit_soul_6_122x150_1',
			nameShort: 'snail_icon__0001_bell_hermit_soul',
			size: {
				x: 122,
				y: 150,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Snare Soul Churchkeeper',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_SNARE_SOUL_CHURCHKEEPER',
		descriptionKey: 'UI.INV_DESC_SNARE_SOUL_CHURCHKEEPER',
		icon: {
			name: 'snail_icon__0000_churchkeeper_soul_8_125x150_1',
			nameShort: 'snail_icon__0000_churchkeeper_soul',
			size: {
				x: 125,
				y: 150,
			},
			padding: {
				x: 2.064629,
				y: 2.07612038,
				z: 1.07611847,
				w: 2.02674866,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Snare Soul Swamp Bug',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_SNARE_SOUL_SWAMP',
		descriptionKey: 'UI.INV_DESC_SNARE_SOUL_SWAMP',
		icon: {
			name: 'snail_icon__0001_bell_swamp_soul_8_131x142_2',
			nameShort: 'snail_icon__0001_bell_swamp_soul',
			size: {
				x: 131,
				y: 142,
			},
			padding: {
				x: 5.07612038,
				y: 0.0429079533,
				z: 6.04290771,
				w: 3.076126,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Flower Heart',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_HEART_BLOOM',
		descriptionKey: 'UI.INV_DESC_HEART_BLOOM',
		icon: {
			name: 'flower_queen_heart_icon0000_9_175x163_1',
			nameShort: 'flower_queen_heart_icon0000',
			size: {
				x: 175,
				y: 163,
			},
			padding: {
				x: 22.02675,
				y: 18.0129128,
				z: 18.0267487,
				w: 12.0761261,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Hunter Heart',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_HEART_HUNTER',
		descriptionKey: 'UI.INV_DESC_HEART_HUNTER',
		icon: {
			name: 'ant_queen_heart_icon0002_8_125x139_1',
			nameShort: 'ant_queen_heart_icon0002',
			size: {
				x: 125,
				y: 139,
			},
			padding: {
				x: 9.07612,
				y: 3.036285,
				z: 10.0761185,
				w: 1.02674866,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Coral Heart',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_HEART_CORAL',
		descriptionKey: 'UI.INV_DESC_HEART_CORAL',
		icon: {
			name: 'coral_king_heart_icon0000_16_136x153_1',
			nameShort: 'coral_king_heart_icon0000',
			size: {
				x: 136,
				y: 153,
			},
			padding: {
				x: 0.0267510414,
				y: 7.02191448,
				z: 7.012909,
				w: 6.0362854,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
	{
		id: 'Clover Heart',
		runtimeType: 'MateriumItem',
		displayNameKey: 'UI.INV_NAME_HEART_CLOVER',
		descriptionKey: 'UI.INV_DESC_HEART_CLOVER',
		icon: {
			name: 'clover_prince_heart0000_8_142x159_1',
			nameShort: 'clover_prince_heart0000',
			size: {
				x: 142,
				y: 159,
			},
			padding: {
				x: 13.0429077,
				y: 11.0267506,
				z: 14.0761185,
				w: 10.0267487,
			},
		},
		isRequiredForCompletion: true,
		isCollected: true,
		isSeen: true,
		isVisibleInCollection: true,
	},
];
export type MateriumSilk = (typeof list)[number];
export const materiumSilk = {
	list,
	byName: Object.fromEntries(list.map((it: any) => [it.id, it])) as Record<MateriumNameSilk, MateriumSilk>,
};

export const materiumIdToNameSilk: Map<number, MateriumNameSilk> = new Map([
	[1, 'Silk'],
	[2, 'Shell Shard'],
	[3, 'Rosary Small'],
	[4, 'Rosary Mid'],
	[5, 'Rosary Big'],
	[6, 'Mossberry'],
	[7, 'Mossberry Stew'],
	[8, 'Pilgrim Rag'],
	[9, 'Smeltstone'],
	[10, 'Rock Roller Item'],
	[11, 'Tool Metal'],
	[12, 'Common Spine'],
	[13, 'Skull King Fragment'],
	[14, 'Beastfly Remains'],
	[15, 'Silver Bellclapper'],
	[16, 'Pale Oil'],
	[17, 'Lifeblood'],
	[18, 'Plasmium Blood'],
	[19, 'Crow Feathers'],
	[20, 'Shell Flower'],
	[21, 'Roach Corpse Item'],
	[22, 'Courier Supplies Generic'],
	[23, 'Courier Supplies Slave'],
	[24, 'Courier Supplies Mask Maker'],
	[25, 'Courier Supplies Gourmand'],
	[26, 'Vintage Nectar'],
	[27, 'Pickled Roach Egg'],
	[28, 'Crustnut'],
	[29, 'Extractor Machine Pins'],
	[30, 'Song Pilgrim Cloak'],
	[31, 'Magnetite'],
	[32, 'Broodmother Remains'],
	[33, 'Enemy Morsel Seared'],
	[34, 'Enemy Morsel Shredded'],
	[35, 'Enemy Morsel Speared'],
	[36, 'Voltstone'],
	[37, 'Snare Soul Bell Hermit'],
	[38, 'Snare Soul Churchkeeper'],
	[39, 'Snare Soul Swamp Bug'],
	[40, 'Flower Heart'],
	[41, 'Hunter Heart'],
	[42, 'Coral Heart'],
	[43, 'Clover Heart'],
]);
export const materiumNamesSilk: MateriumNameSilk[] = materiumIdToNameSilk.values().toArray();
