/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */

export type RespawnPointNameSilk =
	| 'Cage Broken Respawn Marker'
	| 'Cage Kill Respawn Marker'
	| 'Caged Respawn Marker'
	| 'Death Respawn Marker'
	| 'Death Respawn Marker Architect Door'
	| 'Death Respawn Marker Church'
	| 'Death Respawn Marker Garmond'
	| 'Death Respawn Marker Init'
	| 'Death Respawn Marker NonLethal'
	| 'Death Respawn Marker Pinstress'
	| 'Interim Respawn Marker'
	| 'RestBench'
	| 'RestBench (1)'
	| 'RestBench (2)'
	| 'RestBench Festival'
	| 'Silk Heart Memory Respawn Marker'
	| 'TrapBench';

const list = [
	{
		id: 'Cage Broken Respawn Marker',
	},
	{
		id: 'Cage Kill Respawn Marker',
	},
	{
		id: 'Caged Respawn Marker',
	},
	{
		id: 'Death Respawn Marker',
	},
	{
		id: 'Death Respawn Marker Architect Door',
	},
	{
		id: 'Death Respawn Marker Church',
	},
	{
		id: 'Death Respawn Marker Garmond',
	},
	{
		id: 'Death Respawn Marker Init',
	},
	{
		id: 'Death Respawn Marker NonLethal',
	},
	{
		id: 'Death Respawn Marker Pinstress',
	},
	{
		id: 'Interim Respawn Marker',
	},
	{
		id: 'RestBench',
	},
	{
		id: 'RestBench (1)',
	},
	{
		id: 'RestBench (2)',
	},
	{
		id: 'RestBench Festival',
	},
	{
		id: 'Silk Heart Memory Respawn Marker',
	},
	{
		id: 'TrapBench',
	},
];
export type RespawnPointSilk = (typeof list)[number];
export const respawnPointSilk = {
	list,
	byName: Object.fromEntries(list.map((it: any) => [it.id, it])) as Record<RespawnPointNameSilk, RespawnPointSilk>,
};

export const respawnPointIdToNameSilk: Map<number, RespawnPointNameSilk> = new Map([
	[1, 'Cage Broken Respawn Marker'],
	[2, 'Cage Kill Respawn Marker'],
	[3, 'Caged Respawn Marker'],
	[4, 'Death Respawn Marker'],
	[5, 'Death Respawn Marker Architect Door'],
	[6, 'Death Respawn Marker Church'],
	[7, 'Death Respawn Marker Garmond'],
	[8, 'Death Respawn Marker Init'],
	[9, 'Death Respawn Marker NonLethal'],
	[10, 'Death Respawn Marker Pinstress'],
	[11, 'Interim Respawn Marker'],
	[12, 'RestBench'],
	[13, 'RestBench (1)'],
	[14, 'RestBench (2)'],
	[15, 'RestBench Festival'],
	[16, 'Silk Heart Memory Respawn Marker'],
	[17, 'TrapBench'],
]);
export const respawnPointNamesSilk: RespawnPointNameSilk[] = respawnPointIdToNameSilk.values().toArray();
