/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */

import type { SilkSpriteInfoGenerated } from './map-data-silk.generated.types.ts';
import type { MapZoneSilk } from './map-zone-silk.ts';

export interface AreaBackgroundData {
	nameOverride: string | null;
	act3OverlayOptOut: boolean;
	backgroundImage: SilkSpriteInfoGenerated | null;
	act3BackgroundImage: SilkSpriteInfoGenerated | null;
}

export const saveSlotBackgroundSilk: {
	areaBackgrounds: Record<MapZoneSilk, AreaBackgroundData>;
	extraAreaBackgrounds: Record<string, AreaBackgroundData>;
	bellhomeBackgrounds: Record<string, SilkSpriteInfoGenerated>;
} = {
	areaBackgrounds: {
		NONE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: null,
			act3BackgroundImage: null,
		},
		TEST_AREA: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: null,
			act3BackgroundImage: null,
		},
		PATH_OF_BONE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0009_Boneforest_4_353x640_0',
				nameShort: 'Area_Art__0009_Boneforest',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		GREYMOOR: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0007_Greymoor_4_353x640_0',
				nameShort: 'Area_Art__0007_Greymoor',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		SHELLWOOD_THICKET: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0006_Shellwood_4_353x640_0',
				nameShort: 'Area_Art__0006_Shellwood',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		RED_CORAL_GORGE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0005_Coral-Gorge_old_4_71x128_1',
				nameShort: 'Area_Art__0005_Coral-Gorge_old',
				size: {
					x: 71,
					y: 128,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		CITY_OF_SONG: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0004_City-of-Song_4_353x640_0',
				nameShort: 'Area_Art__0004_City-of-Song',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: {
				name: 'Area_Art__0004_City-of-Song_act_3_4_353x640_1',
				nameShort: 'Area_Art__0004_City-of-Song_act_3',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
		},
		THE_SLAB: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0003_The-Slab_4_353x640_0',
				nameShort: 'Area_Art__0003_The-Slab',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		GLOOM: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: null,
			act3BackgroundImage: null,
		},
		DUSTPENS: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_Dustpens_4_353x640_0',
				nameShort: 'Area_Art_Dustpens',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		BELLTOWN: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0014_Bellhart_4_353x640_0',
				nameShort: 'Area_Art__0014_Bellhart',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: {
				name: 'Area_Art__0014_Bellhart_broken_4_353x640_1',
				nameShort: 'Area_Art__0014_Bellhart_broken',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
		},
		HUNTERS_NEST: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0002_Hunters_Nest_4_353x640_0',
				nameShort: 'Area_Art__0002_Hunters_Nest',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		BONETOWN: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0013_Bonebottom_4_353x640_0',
				nameShort: 'Area_Art__0013_Bonebottom',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		MOSS_CAVE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0011_Mosscave_4_353x640_0',
				nameShort: 'Area_Art__0011_Mosscave',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		PHARLOOM_BAY: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0002_Pharloom-Bay_4_353x640_0',
				nameShort: 'Area_Art__0002_Pharloom-Bay',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		DOCKS: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0008_Docks_4_353x640_0',
				nameShort: 'Area_Art__0008_Docks',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		WILDS: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Scorchlands_option_02_4_353x640_0',
				nameShort: 'Area_Art__0001_Scorchlands_option_02',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		WEAVER_SHRINE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0005_Weaver_Shrine_4_353x640_0',
				nameShort: 'Area_Art__0005_Weaver_Shrine',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		BONECHURCH: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0012_Bonechurch_4_353x640_0',
				nameShort: 'Area_Art__0012_Bonechurch',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		MOSSTOWN: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0010_Mosstown_4_353x640_0',
				nameShort: 'Area_Art__0010_Mosstown',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		LIBRARY: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0002_Library_4_353x640_0',
				nameShort: 'Area_Art__0002_Library',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		CLOVER: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Clover_4_353x640_1',
				nameShort: 'Area_Art__0001_Clover',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		UNDERSTORE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_Understore_4_353x640_0',
				nameShort: 'Area_Art_Understore',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		COG_CORE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_Cog_Core_4_353x640_0',
				nameShort: 'Area_Art_Cog_Core',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: {
				name: 'Area_Art_Cog_Core_Act3_4_353x640_0',
				nameShort: 'Area_Art_Cog_Core_Act3',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
		},
		PEAK: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_Peak_4_353x640_0',
				nameShort: 'Area_Art_Peak',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		DUST_MAZE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_Dust_Maze_4_353x640_0',
				nameShort: 'Area_Art_Dust_Maze',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		WARD: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__Ward_4_353x640_0',
				nameShort: 'Area_Art__Ward',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		HANG: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_Hang_4_353x640_0',
				nameShort: 'Area_Art_Hang',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		ARBORIUM: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_Arborium_4_353x640_0',
				nameShort: 'Area_Art_Arborium',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		CRADLE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Cradle_Act1_4_353x640_1',
				nameShort: 'Area_Art__0001_Cradle_Act1',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: {
				name: 'Area_Art__0001_Cradle_Destroyed_4_353x640_1',
				nameShort: 'Area_Art__0001_Cradle_Destroyed',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
		},
		PILGRIMS_REST: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_Pilgrims_Rest_4_353x640_0',
				nameShort: 'Area_Art_Pilgrims_Rest',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: {
				name: 'Area_Art_Pilgrims_Rest_act3_4_353x640_1',
				nameShort: 'Area_Art_Pilgrims_Rest_act3',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
		},
		HALFWAY_HOUSE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_Halfway_4_353x640_0',
				nameShort: 'Area_Art_Halfway',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		JUDGE_STEPS: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0005_Coral-Gorge_4_353x640_0',
				nameShort: 'Area_Art__0005_Coral-Gorge',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		MEMORY: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Memory_4_353x640_1',
				nameShort: 'Area_Art__0001_Memory',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		CRAWLSPACE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Crawl_4_353x640_1',
				nameShort: 'Area_Art__0001_Crawl',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: {
				name: 'Area Art_Crawl_Act3_4_353x640_1',
				nameShort: 'Area Art_Crawl_Act3',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
		},
		WISP: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Wisp_4_353x640_1',
				nameShort: 'Area_Art__0001_Wisp',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		SWAMP: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Swamp_4_353x640_1',
				nameShort: 'Area_Art__0001_Swamp',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		ABYSS: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Abyss_4_353x640_1',
				nameShort: 'Area_Art__0001_Abyss',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		AQUEDUCT: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Aqueduct_4_353x640_1',
				nameShort: 'Area_Art__0001_Aqueduct',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		SURFACE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: null,
			act3BackgroundImage: null,
		},
		FRONT_GATE: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: null,
			act3BackgroundImage: null,
		},
		CORAL_CAVERNS: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: null,
			act3BackgroundImage: null,
		},
	},
	extraAreaBackgrounds: {
		None: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: null,
			act3BackgroundImage: null,
		},
		PinstressHut: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0003_Pinstress_4_353x640_1',
				nameShort: 'Area_Art__0003_Pinstress',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		SeamstressHut: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0003_Seamstress_4_353x640_1',
				nameShort: 'Area_Art__0003_Seamstress',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		Bonegrave: {
			nameOverride: 'Map Zones.BONETOWN_GRAVEYARD',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0003__Bonegrave_4_353x640_1',
				nameShort: 'Area_Art__0003__Bonegrave',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		GrandGate: {
			nameOverride: 'Map Zones.FRONT_GATE',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__GrandGate_4_353x640_1',
				nameShort: 'Area_Art__GrandGate',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		TubeHub: {
			nameOverride: 'Map Zones.EXTRA_TUBEHUB',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_Tube_Hub_4_353x640_0',
				nameShort: 'Area_Art_Tube_Hub',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: {
				name: 'Area_Art_Tube_Hub_act3_4_353x640_1',
				nameShort: 'Area_Art_Tube_Hub_act3',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
		},
		Organ: {
			nameOverride: 'Map Zones.ORGAN',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Organ_4_353x640_0',
				nameShort: 'Area_Art__0001_Organ',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		Fleatopia: {
			nameOverride: 'Map Zones.FLEATOPIA',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Fleatopia_4_353x640_1',
				nameShort: 'Area_Art__0001_Fleatopia',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		FleaFestival: {
			nameOverride: 'Map Zones.FLEA_FESTIVAL',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Flea_Festival_4_353x640_1',
				nameShort: 'Area_Art__0001_Flea_Festival',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		Bellvein: {
			nameOverride: 'Map Zones.BELLVEIN',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_Bellvein_4_353x640_1',
				nameShort: 'Area_Art_Bellvein',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		SlabCell: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_Slab_Cell_4_353x640_1',
				nameShort: 'Area_Art_Slab_Cell',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		Enclave: {
			nameOverride: 'Map Zones.ENCLAVE',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Enclave_4_353x640_1',
				nameShort: 'Area_Art__0001_Enclave',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: {
				name: 'Area_Art__0001_Enclave_Act_3_4_353x640_1',
				nameShort: 'Area_Art__0001_Enclave_Act_3',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
		},
		CitadelShrine: {
			nameOverride: 'Map Zones.CITADELSHRINE',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0008_Enclave_Bellshrine_4_353x640_1',
				nameShort: 'Area_Art__0008_Enclave_Bellshrine',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		CoralTower: {
			nameOverride: 'Map Zones.RED_CORAL_TOWER',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Coral_Tower_4_353x640_1',
				nameShort: 'Area_Art__0001_Coral_Tower',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		BonetownBroken: {
			nameOverride: null,
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0013_Bonebottom_Broken_4_354x640_1',
				nameShort: 'Area_Art__0013_Bonebottom_Broken',
				size: {
					x: 354,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		CoralBellshrine: {
			nameOverride: 'Map Zones.RED_CORAL_GORGE',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Coral_Caverns_4_353x640_1',
				nameShort: 'Area_Art__0001_Coral_Caverns',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		Bellhome: {
			nameOverride: 'Map Zones.BELLHOME',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0014_Bellhome_4_353x640_1',
				nameShort: 'Area_Art__0014_Bellhome',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		Citadelstation: {
			nameOverride: 'Map Zones.CITADEL_STATION',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Citadel_station_4_353x640_1',
				nameShort: 'Area_Art__0001_Citadel_station',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: {
				name: 'Area_Art__0001_Citadel_station_act_3_4_353x640_1',
				nameShort: 'Area_Art__0001_Citadel_station_act_3',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
		},
		MemoryRed: {
			nameOverride: 'Map Zones.MEMORY_RED',
			act3OverlayOptOut: true,
			backgroundImage: {
				name: 'Area_Art__0001_RedMemory_4_353x640_1',
				nameShort: 'Area_Art__0001_RedMemory',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		AboveCradle: {
			nameOverride: 'Map Zones.ABOVE_CRADLE',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Border_Caves_4_353x640_1',
				nameShort: 'Area_Art__0001_Border_Caves',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		SprintmasterCave: {
			nameOverride: 'Map Zones.SPRINTMASTER_CAVE',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0001_Sprintmaster_Cave_4_353x640_1',
				nameShort: 'Area_Art__0001_Sprintmaster_Cave',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		BelltownHaunted: {
			nameOverride: 'Map Zones.BELLTOWN_HAUNTED',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art__0014_Bellhart_Haunted_4_353x640_1',
				nameShort: 'Area_Art__0014_Bellhart_Haunted',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
		WhiteLake: {
			nameOverride: 'Map Zones.WHITELAKE',
			act3OverlayOptOut: false,
			backgroundImage: {
				name: 'Area_Art_White_Lake_4_353x640_1',
				nameShort: 'Area_Art_White_Lake',
				size: {
					x: 353,
					y: 640,
				},
				padding: {
					x: 0,
					y: 0,
					z: 0,
					w: 0,
				},
			},
			act3BackgroundImage: null,
		},
	},
	bellhomeBackgrounds: {
		None: {
			name: 'Area_Art__0014_Bellhome_4_353x640_1',
			nameShort: 'Area_Art__0014_Bellhome',
			size: {
				x: 353,
				y: 640,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		Red: {
			name: 'Area_Art__0014_Bellhome_red_4_353x640_1',
			nameShort: 'Area_Art__0014_Bellhome_red',
			size: {
				x: 353,
				y: 640,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		White: {
			name: 'Area_Art__0014_Bellhome_white_4_353x640_1',
			nameShort: 'Area_Art__0014_Bellhome_white',
			size: {
				x: 353,
				y: 640,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		DarkGrey: {
			name: 'Area_Art__0014_Bellhome_black_4_353x640_1',
			nameShort: 'Area_Art__0014_Bellhome_black',
			size: {
				x: 353,
				y: 640,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		Bronze: {
			name: 'Area_Art__0014_Bellhome_bronze_4_353x640_1',
			nameShort: 'Area_Art__0014_Bellhome_bronze',
			size: {
				x: 353,
				y: 640,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		Blue: {
			name: 'Area_Art__0014_Bellhome_blue_4_353x640_1',
			nameShort: 'Area_Art__0014_Bellhome_blue',
			size: {
				x: 353,
				y: 640,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
		Chrome: {
			name: 'Area_Art__0014_Bellhome_chrome_4_353x640_1',
			nameShort: 'Area_Art__0014_Bellhome_chrome',
			size: {
				x: 353,
				y: 640,
			},
			padding: {
				x: 0,
				y: 0,
				z: 0,
				w: 0,
			},
		},
	},
};
