/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */

export type SceneDataGeoRockNameSilk =
	| 'Geo Rock 3'
	| 'Geo Rock 1 (1)'
	| 'Geo Rock 2'
	| 'Geo Rock 1'
	| 'Geo Rock 2 (1)'
	| 'Geo Rock Deepnest'
	| 'Geo Rock Deepnest (1)';

const list = [
	{
		sceneName: 'Bone_01c',
		id: 'Geo Rock 3',
	},
	{
		sceneName: 'Bone_01c',
		id: 'Geo Rock 1 (1)',
	},
	{
		sceneName: 'Bone_04',
		id: 'Geo Rock 3',
	},
	{
		sceneName: 'Aspid_01',
		id: 'Geo Rock 2',
	},
	{
		sceneName: 'Bone_16',
		id: 'Geo Rock 1',
	},
	{
		sceneName: 'Bone_16',
		id: 'Geo Rock 2 (1)',
	},
	{
		sceneName: 'Bone_16',
		id: 'Geo Rock 2',
	},
	{
		sceneName: 'Bone_14',
		id: 'Geo Rock 1',
	},
	{
		sceneName: 'Bone_08',
		id: 'Geo Rock 1',
	},
	{
		sceneName: 'Bone_08',
		id: 'Geo Rock 2',
	},
	{
		sceneName: 'Bone_East_15',
		id: 'Geo Rock 2',
	},
	{
		sceneName: 'Bone_East_15',
		id: 'Geo Rock 1',
	},
	{
		sceneName: 'Bone_East_08',
		id: 'Geo Rock 2',
	},
	{
		sceneName: 'Greymoor_01',
		id: 'Geo Rock Deepnest',
	},
	{
		sceneName: 'Greymoor_15',
		id: 'Geo Rock 1',
	},
	{
		sceneName: 'Greymoor_04',
		id: 'Geo Rock Deepnest',
	},
	{
		sceneName: 'Greymoor_05',
		id: 'Geo Rock Deepnest',
	},
	{
		sceneName: 'Greymoor_06',
		id: 'Geo Rock Deepnest',
	},
	{
		sceneName: 'Greymoor_07',
		id: 'Geo Rock Deepnest',
	},
	{
		sceneName: 'Shellwood_26',
		id: 'Geo Rock 3',
	},
	{
		sceneName: 'Dust_02',
		id: 'Geo Rock Deepnest',
	},
	{
		sceneName: 'Dust_10',
		id: 'Geo Rock Deepnest',
	},
	{
		sceneName: 'Greymoor_11',
		id: 'Geo Rock Deepnest (1)',
	},
	{
		sceneName: 'Coral_12',
		id: 'Geo Rock Deepnest',
	},
	{
		sceneName: 'Aqueduct_08',
		id: 'Geo Rock 1 (1)',
	},
	{
		sceneName: 'Aqueduct_08',
		id: 'Geo Rock 1',
	},
	{
		sceneName: 'Aqueduct_08',
		id: 'Geo Rock 3',
	},
	{
		sceneName: 'Shadow_20',
		id: 'Geo Rock 1',
	},
	{
		sceneName: 'Shadow_20',
		id: 'Geo Rock 3',
	},
	{
		sceneName: 'Shadow_05',
		id: 'Geo Rock Deepnest',
	},
	{
		sceneName: 'Shadow_14',
		id: 'Geo Rock 1',
	},
	{
		sceneName: 'Shadow_19',
		id: 'Geo Rock 1',
	},
	{
		sceneName: 'Shadow_19',
		id: 'Geo Rock 3',
	},
];
export type SceneDataGeoRockSilk = (typeof list)[number];
export const sceneDataGeoRockSilk = {
	list,
	byName: Object.fromEntries(list.map((it: any) => [it.id, it])) as Record<
		SceneDataGeoRockNameSilk,
		SceneDataGeoRockSilk
	>,
};

export const sceneDataGeoRockIdToNameSilk: Map<number, SceneDataGeoRockNameSilk> = new Map([
	[1, 'Geo Rock 3'],
	[2, 'Geo Rock 1 (1)'],
	[1, 'Geo Rock 3'],
	[3, 'Geo Rock 2'],
	[4, 'Geo Rock 1'],
	[5, 'Geo Rock 2 (1)'],
	[3, 'Geo Rock 2'],
	[4, 'Geo Rock 1'],
	[4, 'Geo Rock 1'],
	[3, 'Geo Rock 2'],
	[3, 'Geo Rock 2'],
	[4, 'Geo Rock 1'],
	[3, 'Geo Rock 2'],
	[6, 'Geo Rock Deepnest'],
	[4, 'Geo Rock 1'],
	[6, 'Geo Rock Deepnest'],
	[6, 'Geo Rock Deepnest'],
	[6, 'Geo Rock Deepnest'],
	[6, 'Geo Rock Deepnest'],
	[1, 'Geo Rock 3'],
	[6, 'Geo Rock Deepnest'],
	[6, 'Geo Rock Deepnest'],
	[7, 'Geo Rock Deepnest (1)'],
	[6, 'Geo Rock Deepnest'],
	[2, 'Geo Rock 1 (1)'],
	[4, 'Geo Rock 1'],
	[1, 'Geo Rock 3'],
	[4, 'Geo Rock 1'],
	[1, 'Geo Rock 3'],
	[6, 'Geo Rock Deepnest'],
	[4, 'Geo Rock 1'],
	[4, 'Geo Rock 1'],
	[1, 'Geo Rock 3'],
]);
export const sceneDataGeoRockNamesSilk: SceneDataGeoRockNameSilk[] = sceneDataGeoRockIdToNameSilk.values().toArray();
