/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */

export type SceneDataIntNameSilk =
	| 'Shell Shard Fossil Large Uni'
	| 'Shell Shard Fossil Tiny Bumpy'
	| 'Shell Shard Fossil Tiny Egg'
	| 'Shell Shard Fossil Tiny Front'
	| 'Shell Shard Fossil Mid (1)'
	| 'Churchkeeper Basement'
	| 'rosary_string_small_half'
	| 'rosary_shrine_small'
	| 'rosary_string_medium'
	| 'Churchkeeper'
	| 'Fixer Pilgrim Bench Repair'
	| 'Fixer Pilgrim'
	| 'Fixer NPC Standing'
	| 'Mapper NPC'
	| 'Generic Pilgrim Round'
	| 'Generic Pilgrim Stomper'
	| 'Shell Shard Fossil Big'
	| 'Bellway Pilgrim'
	| 'rosary_string_small_half (2)'
	| 'rosary_string_small'
	| 'rosary_string_small_half (1)'
	| 'Shell Shard Fossil Tiny Front (2)'
	| 'Shell Shard Fossil Tiny Front (3)'
	| 'rosary_string_small_mixed'
	| 'Caravan Troup Member Tall'
	| 'Caravan Troup Member Short'
	| 'Fixer Sitting Bone_10'
	| 'rosary_string_small (1)'
	| 'rosary_string_small (2)'
	| 'Bellshrine Sequence'
	| 'Shell Fossil Mimic AppearVariant'
	| 'Shell Fossil Mimic'
	| 'rosary_cache_hang_bell'
	| 'rosary_cache_bell_ground (1)'
	| 'rosary_cache_bell_ground'
	| 'Thief NPC Saved'
	| 'Pin Challenge'
	| 'Song Shard Barrel'
	| 'Shell Shard Fossil Dock (2)'
	| 'Shell Shard Fossil Dock (1)'
	| 'Shell Shard Fossil Dock (3)'
	| 'Shell Shard Fossil Mid'
	| 'ant_rosary_string (2)'
	| 'ant_rosary_string'
	| 'ant_rosary_string (1)'
	| 'Sherma Docks NPC'
	| 'Generic Pilgrim Large'
	| 'Seth Sit NPC Greymoor'
	| 'Hornet_cage_rect_lift_greymoor'
	| 'rosary_string_small_half (3)'
	| 'rosary_string_small_half (6)'
	| 'rosary_string_small_half (8)'
	| 'rosary_string_small_half (7)'
	| 'HH Bartender'
	| 'HH Patron Right'
	| 'HH Patron Left'
	| 'Garmond Sleep NPC'
	| 'scissor_string (7)'
	| 'scissor_string (4)'
	| 'scissor_string (6)'
	| 'scissor_string (5)'
	| 'scissor_string (2)'
	| 'scissor_string (8)'
	| 'scissor_string (9)'
	| 'scissor_string (1)'
	| 'Mapper StandGuard NPC'
	| 'Shell Shard Fossil Tiny Egg (1)'
	| 'ant_item_string'
	| 'ant_shell_shard_string (2)'
	| 'ant_shell_shard_string (1)'
	| 'ant_shell_shard_string'
	| 'ant_shell_shard_string (3)'
	| 'Pilgrim Fisher NPC Walker'
	| 'Courier Short Bellhart'
	| 'Belltown Greeter Act3'
	| 'Shell Shard Fossil Tiny Bumpy (1)'
	| 'Hornet_cage_rect_lift'
	| 'Rosary Pilgrim'
	| 'Shell Shard Fossil Tiny Bumpy (2)'
	| 'Bellshrine Sequence Bellhart'
	| 'ant_rosary_string (3)'
	| 'ant_rosary_string_medium'
	| 'ant_rosary_string_medium (1)'
	| 'ant_rosary_string_medium (2)'
	| 'ant_rosary_string_medium (3)'
	| 'ant_rosary_string_medium Variant'
	| 'ant_rosary_string_large (1)'
	| 'ant_rosary_string_large'
	| 'rosary_string_small_half (4)'
	| 'rosary_string_small_half (5)'
	| 'Courier Short'
	| 'NPC'
	| 'Green Prince Sit'
	| 'Courier Tall'
	| 'Hornet_cage_rect_lift_organ (1)'
	| 'Shell Shard Fossil Dustpen Short'
	| 'Shell Shard Fossil Dustpen Tall'
	| 'library_lift_large'
	| 'Library Sliding Plat (1)'
	| 'Library Sliding Plat (5)'
	| 'Library Sliding Plat (2)'
	| 'Library Sliding Plat'
	| 'Library Sliding Plat Tall (1)'
	| 'Library Sliding Plat Tall (2)'
	| 'Library Sliding Plat Tall'
	| 'Toll_machine_silk_ration'
	| 'Song Shard Under Chest'
	| 'Hero Treadmill Rosaries Paid'
	| 'Understore Large Worker'
	| 'Song Shard Under Chest (1)'
	| 'under_lift_large'
	| 'Song Shard Barrel (1)'
	| 'Shell Shard Fossil Tiny Egg (2)'
	| 'jail_gate_breakable (2)'
	| 'jail_gate_breakable (3)'
	| 'Shell Shard Fossil Tiny Front (1)'
	| 'rosary_string_medium (1)'
	| 'Music Box Sequence - EDITED'
	| 'Shower Lever 2'
	| 'Shower Lever'
	| 'Green Prince Stand Song_04'
	| 'Mapper NPC (1)'
	| 'Enclave Simple NPC Tall'
	| 'Enclave Pilgrim Small'
	| 'Enclave Simple NPC Short Horned'
	| 'Sherma Healer'
	| 'Enclave Simple NPC Standard'
	| 'Enclave Simple NPC Large'
	| 'rosary_bucket_library'
	| 'Library Sliding Plat (3)'
	| 'Shell Shard Fossil Coral Conch (1)'
	| 'Shell Shard Fossil Coral Conch'
	| 'Pinstress Interior Sit NPC'
	| 'Library Statue NPC'
	| 'rosary_string_large_mixed Variant'
	| 'rosary_string_large_full Variant'
	| 'Shell Shard Fossil Dustpen Tall (2)'
	| 'Shell Shard Fossil Dustpen Tall (1)'
	| 'Caravan Troup Member Tall - Act 2'
	| 'Caravan Troup Member Tall - Act 3'
	| 'Caravan Troup Member Short Fleatopia'
	| 'Seth Sit NPC Fleatopia'
	| 'Slab Prisoner'
	| 'Thief NPC Slab Saferoom'
	| 'Shell Shard Fossil Mid Variant'
	| 'Forge Worker Sauna NPC'
	| 'Shell Shard Fossil Tiny Egg (3)'
	| 'Dust Traders'
	| 'jail_gate_breakable'
	| 'Snail Shamans Set'
	| 'Inspect Region - Void Tendrils'
	| 'Ballow Diving Bell Repair NPC'
	| 'Sprintmaster Runner'
	| 'Ant Queen BG NPC'
	| 'rosary_cache_hang'
	| 'Shell Shard Fossil Beast';

const list = [
	{
		sceneName: 'Tut_01',
		id: 'Shell Shard Fossil Large Uni',
	},
	{
		sceneName: 'Tut_02',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Tut_02',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Tut_02',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Tut_01b',
		id: 'Shell Shard Fossil Mid (1)',
	},
	{
		sceneName: 'Tut_01b',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Tut_01b',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Tut_03',
		id: 'Churchkeeper Basement',
	},
	{
		sceneName: 'Bonetown',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Bonetown',
		id: 'rosary_shrine_small',
	},
	{
		sceneName: 'Bonetown',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Bonetown',
		id: 'Churchkeeper',
	},
	{
		sceneName: 'Bonetown',
		id: 'Fixer Pilgrim Bench Repair',
	},
	{
		sceneName: 'Bonetown',
		id: 'Fixer Pilgrim',
	},
	{
		sceneName: 'Bonetown',
		id: 'Fixer NPC Standing',
	},
	{
		sceneName: 'Bonetown',
		id: 'Mapper NPC',
	},
	{
		sceneName: 'Bonetown',
		id: 'Generic Pilgrim Round',
	},
	{
		sceneName: 'Bonetown',
		id: 'Generic Pilgrim Stomper',
	},
	{
		sceneName: 'Bonetown',
		id: 'Shell Shard Fossil Big',
	},
	{
		sceneName: 'Bellway_01',
		id: 'Bellway Pilgrim',
	},
	{
		sceneName: 'Bone_01',
		id: 'rosary_string_small_half (2)',
	},
	{
		sceneName: 'Bone_01',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Bone_01',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Bone_01c',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Bone_01c',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Bone_04',
		id: 'Shell Shard Fossil Tiny Front (2)',
	},
	{
		sceneName: 'Bone_04',
		id: 'Shell Shard Fossil Tiny Front (3)',
	},
	{
		sceneName: 'Bone_04',
		id: 'Mapper NPC',
	},
	{
		sceneName: 'Bone_11',
		id: 'rosary_string_small_mixed',
	},
	{
		sceneName: 'Bone_11',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Bone_10',
		id: 'rosary_shrine_small',
	},
	{
		sceneName: 'Bone_10',
		id: 'Caravan Troup Member Tall',
	},
	{
		sceneName: 'Bone_10',
		id: 'Caravan Troup Member Short',
	},
	{
		sceneName: 'Bone_10',
		id: 'Fixer Sitting Bone_10',
	},
	{
		sceneName: 'Mosstown_01',
		id: 'rosary_string_small (1)',
	},
	{
		sceneName: 'Mosstown_01',
		id: 'rosary_string_small (2)',
	},
	{
		sceneName: 'Bone_01b',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Bone_01b',
		id: 'rosary_shrine_small',
	},
	{
		sceneName: 'Bone_01b',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Mosstown_02',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Mosstown_02',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Bellshrine',
		id: 'Bellshrine Sequence',
	},
	{
		sceneName: 'Bone_06',
		id: 'Shell Fossil Mimic AppearVariant',
	},
	{
		sceneName: 'Bone_14',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Bone_14',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Bone_14',
		id: 'Shell Fossil Mimic',
	},
	{
		sceneName: 'Bone_07',
		id: 'Shell Shard Fossil Large Uni',
	},
	{
		sceneName: 'Bone_19',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Bone_19',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Bone_19',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Belltown_basement_03',
		id: 'rosary_cache_hang_bell',
	},
	{
		sceneName: 'Belltown_basement_03',
		id: 'rosary_cache_bell_ground (1)',
	},
	{
		sceneName: 'Belltown_basement_03',
		id: 'rosary_cache_bell_ground',
	},
	{
		sceneName: 'Ant_02',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Ant_02',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Bone_12',
		id: 'Thief NPC Saved',
	},
	{
		sceneName: 'Bone_12',
		id: 'Pin Challenge',
	},
	{
		sceneName: 'Dock_01',
		id: 'Song Shard Barrel',
	},
	{
		sceneName: 'Bone_East_01',
		id: 'Mapper NPC',
	},
	{
		sceneName: 'Room_Forge',
		id: 'Song Shard Barrel',
	},
	{
		sceneName: 'Dock_06_Church',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Dock_06_Church',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Dock_06_Church',
		id: 'rosary_string_small (1)',
	},
	{
		sceneName: 'Dock_06_Church',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Bone_East_13',
		id: 'Shell Shard Fossil Dock (2)',
	},
	{
		sceneName: 'Bone_East_13',
		id: 'Shell Shard Fossil Dock (1)',
	},
	{
		sceneName: 'Bone_East_13',
		id: 'Shell Shard Fossil Dock (3)',
	},
	{
		sceneName: 'Bone_East_03',
		id: 'Shell Fossil Mimic',
	},
	{
		sceneName: 'Ant_05b',
		id: 'rosary_shrine_small',
	},
	{
		sceneName: 'Bellshrine_05',
		id: 'Bellshrine Sequence',
	},
	{
		sceneName: 'Bone_East_02b',
		id: 'Shell Shard Fossil Mid',
	},
	{
		sceneName: 'Bone_East_07',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Bone_East_16',
		id: 'ant_rosary_string (2)',
	},
	{
		sceneName: 'Bone_East_16',
		id: 'ant_rosary_string',
	},
	{
		sceneName: 'Bone_East_16',
		id: 'ant_rosary_string (1)',
	},
	{
		sceneName: 'Bone_East_17b',
		id: 'ant_rosary_string',
	},
	{
		sceneName: 'Bone_East_17b',
		id: 'ant_rosary_string (1)',
	},
	{
		sceneName: 'Bone_East_17',
		id: 'ant_rosary_string',
	},
	{
		sceneName: 'Bone_East_17',
		id: 'ant_rosary_string (1)',
	},
	{
		sceneName: 'Bone_East_10',
		id: 'Sherma Docks NPC',
	},
	{
		sceneName: 'Bone_East_10',
		id: 'Generic Pilgrim Large',
	},
	{
		sceneName: 'Bone_East_14',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Bone_East_14',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Bone_East_14',
		id: 'Shell Fossil Mimic',
	},
	{
		sceneName: 'Bone_East_14b',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Bone_East_14b',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Greymoor_02',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Greymoor_02',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Greymoor_02',
		id: 'Seth Sit NPC Greymoor',
	},
	{
		sceneName: 'Greymoor_03',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Greymoor_03',
		id: 'Hornet_cage_rect_lift_greymoor',
	},
	{
		sceneName: 'Greymoor_03',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Greymoor_15b',
		id: 'rosary_string_small_half (2)',
	},
	{
		sceneName: 'Greymoor_15b',
		id: 'rosary_string_small_half (3)',
	},
	{
		sceneName: 'Greymoor_15b',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Greymoor_15b',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Room_CrowCourt',
		id: 'rosary_string_small_half (6)',
	},
	{
		sceneName: 'Room_CrowCourt',
		id: 'rosary_string_small_half (8)',
	},
	{
		sceneName: 'Room_CrowCourt',
		id: 'rosary_string_small_half (7)',
	},
	{
		sceneName: 'Room_CrowCourt',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Room_CrowCourt',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Room_CrowCourt',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Room_CrowCourt',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Halfway_01',
		id: 'HH Bartender',
	},
	{
		sceneName: 'Halfway_01',
		id: 'HH Patron Right',
	},
	{
		sceneName: 'Halfway_01',
		id: 'HH Patron Left',
	},
	{
		sceneName: 'Greymoor_05',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Greymoor_05',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Greymoor_05',
		id: 'Garmond Sleep NPC',
	},
	{
		sceneName: 'Greymoor_07',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Greymoor_07',
		id: 'rosary_shrine_small',
	},
	{
		sceneName: 'Greymoor_07',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Greymoor_20b',
		id: 'scissor_string (7)',
	},
	{
		sceneName: 'Greymoor_20b',
		id: 'scissor_string (4)',
	},
	{
		sceneName: 'Greymoor_20b',
		id: 'scissor_string (6)',
	},
	{
		sceneName: 'Greymoor_20b',
		id: 'scissor_string (5)',
	},
	{
		sceneName: 'Greymoor_20c',
		id: 'scissor_string (4)',
	},
	{
		sceneName: 'Greymoor_20c',
		id: 'scissor_string (2)',
	},
	{
		sceneName: 'Greymoor_20c',
		id: 'scissor_string (7)',
	},
	{
		sceneName: 'Greymoor_20c',
		id: 'scissor_string (8)',
	},
	{
		sceneName: 'Greymoor_20c',
		id: 'scissor_string (9)',
	},
	{
		sceneName: 'Greymoor_20c',
		id: 'scissor_string (5)',
	},
	{
		sceneName: 'Greymoor_20c',
		id: 'scissor_string (6)',
	},
	{
		sceneName: 'Greymoor_20c',
		id: 'scissor_string (1)',
	},
	{
		sceneName: 'Greymoor_08',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Greymoor_08',
		id: 'Mapper StandGuard NPC',
	},
	{
		sceneName: 'Greymoor_16',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Greymoor_16',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Greymoor_16',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Greymoor_16',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Greymoor_16',
		id: 'Shell Shard Fossil Tiny Egg (1)',
	},
	{
		sceneName: 'Ant_04_left',
		id: 'ant_rosary_string (1)',
	},
	{
		sceneName: 'Ant_04_left',
		id: 'ant_item_string',
	},
	{
		sceneName: 'Ant_04_left',
		id: 'ant_rosary_string',
	},
	{
		sceneName: 'Ant_04_mid',
		id: 'Mapper NPC',
	},
	{
		sceneName: 'Ant_04',
		id: 'ant_shell_shard_string (2)',
	},
	{
		sceneName: 'Ant_04',
		id: 'ant_shell_shard_string (1)',
	},
	{
		sceneName: 'Ant_Merchant',
		id: 'ant_shell_shard_string',
	},
	{
		sceneName: 'Ant_Merchant',
		id: 'ant_shell_shard_string (2)',
	},
	{
		sceneName: 'Ant_Merchant',
		id: 'ant_shell_shard_string (1)',
	},
	{
		sceneName: 'Ant_Merchant',
		id: 'ant_shell_shard_string (3)',
	},
	{
		sceneName: 'Greymoor_22',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Greymoor_22',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Bellshrine_02',
		id: 'Bellshrine Sequence',
	},
	{
		sceneName: 'Belltown',
		id: 'Pilgrim Fisher NPC Walker',
	},
	{
		sceneName: 'Belltown',
		id: 'Courier Short Bellhart',
	},
	{
		sceneName: 'Belltown',
		id: 'Belltown Greeter Act3',
	},
	{
		sceneName: 'Belltown',
		id: 'Mapper NPC',
	},
	{
		sceneName: 'Belltown_07',
		id: 'rosary_cache_hang_bell',
	},
	{
		sceneName: 'Shellwood_01',
		id: 'Shell Shard Fossil Tiny Bumpy (1)',
	},
	{
		sceneName: 'Shellwood_01',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Shellwood_01',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Shellwood_01',
		id: 'Mapper StandGuard NPC',
	},
	{
		sceneName: 'Shellwood_01b',
		id: 'Hornet_cage_rect_lift',
	},
	{
		sceneName: 'Shellwood_02',
		id: 'Hornet_cage_rect_lift',
	},
	{
		sceneName: 'Shellwood_16',
		id: 'Mapper NPC',
	},
	{
		sceneName: 'Shellgrave',
		id: 'Rosary Pilgrim',
	},
	{
		sceneName: 'Crawl_01',
		id: 'Mapper NPC',
	},
	{
		sceneName: 'Room_Caravan_Interior',
		id: 'Caravan Troup Member Tall',
	},
	{
		sceneName: 'Shellwood_11',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Shellwood_11',
		id: 'Shell Shard Fossil Tiny Bumpy (2)',
	},
	{
		sceneName: 'Shellwood_11',
		id: 'Shell Shard Fossil Tiny Bumpy (1)',
	},
	{
		sceneName: 'Shellwood_11',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Shellwood_11',
		id: 'Shell Shard Fossil Mid',
	},
	{
		sceneName: 'Belltown_04',
		id: 'rosary_cache_bell_ground',
	},
	{
		sceneName: 'Belltown_04',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Belltown_04',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Belltown_Shrine',
		id: 'Bellshrine Sequence Bellhart',
	},
	{
		sceneName: 'Ant_21',
		id: 'ant_rosary_string',
	},
	{
		sceneName: 'Ant_21',
		id: 'ant_rosary_string (3)',
	},
	{
		sceneName: 'Ant_21',
		id: 'ant_rosary_string_medium',
	},
	{
		sceneName: 'Ant_21',
		id: 'ant_rosary_string_medium (1)',
	},
	{
		sceneName: 'Ant_21',
		id: 'ant_rosary_string_medium (2)',
	},
	{
		sceneName: 'Ant_21',
		id: 'ant_rosary_string_medium (3)',
	},
	{
		sceneName: 'Ant_21',
		id: 'ant_rosary_string_medium Variant',
	},
	{
		sceneName: 'Ant_21',
		id: 'ant_rosary_string_large (1)',
	},
	{
		sceneName: 'Ant_21',
		id: 'ant_rosary_string_large',
	},
	{
		sceneName: 'Bonegrave',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Bonegrave',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Chapel_Wanderer',
		id: 'rosary_string_small_half (4)',
	},
	{
		sceneName: 'Chapel_Wanderer',
		id: 'rosary_string_small_half (5)',
	},
	{
		sceneName: 'Chapel_Wanderer',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Chapel_Wanderer',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Aspid_01',
		id: 'Courier Short',
	},
	{
		sceneName: 'Greymoor_24',
		id: 'NPC',
	},
	{
		sceneName: 'Dust_02',
		id: 'Green Prince Sit',
	},
	{
		sceneName: 'Dust_02',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Dust_02',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Dust_04',
		id: 'Shell Shard Fossil Tiny Bumpy (1)',
	},
	{
		sceneName: 'Dust_04',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Dust_04',
		id: 'Courier Tall',
	},
	{
		sceneName: 'Dust_03',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Dust_03',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Dust_03',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Dust_03',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Dust_05',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Dust_05',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Dust_06',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Dust_06',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Dust_06',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Organ_01',
		id: 'Hornet_cage_rect_lift_organ (1)',
	},
	{
		sceneName: 'Library_12',
		id: 'Shell Shard Fossil Dustpen Short',
	},
	{
		sceneName: 'Library_12',
		id: 'Shell Shard Fossil Dustpen Tall',
	},
	{
		sceneName: 'Library_12',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Library_12',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Library_11',
		id: 'library_lift_large',
	},
	{
		sceneName: 'Library_13',
		id: 'Song Shard Barrel',
	},
	{
		sceneName: 'Library_03',
		id: 'Library Sliding Plat (1)',
	},
	{
		sceneName: 'Library_03',
		id: 'Library Sliding Plat (5)',
	},
	{
		sceneName: 'Library_03',
		id: 'Library Sliding Plat (2)',
	},
	{
		sceneName: 'Library_03',
		id: 'Library Sliding Plat',
	},
	{
		sceneName: 'Library_03',
		id: 'Library Sliding Plat Tall (1)',
	},
	{
		sceneName: 'Library_03',
		id: 'Library Sliding Plat Tall (2)',
	},
	{
		sceneName: 'Library_03',
		id: 'Library Sliding Plat Tall',
	},
	{
		sceneName: 'Song_29',
		id: 'Toll_machine_silk_ration',
	},
	{
		sceneName: 'Library_02',
		id: 'Library Sliding Plat (2)',
	},
	{
		sceneName: 'Library_02',
		id: 'Library Sliding Plat (1)',
	},
	{
		sceneName: 'Bellshrine_Enclave',
		id: 'Bellshrine Sequence',
	},
	{
		sceneName: 'Song_11',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Song_11',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Song_11',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Song_07',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Song_01b',
		id: 'rosary_string_small_mixed',
	},
	{
		sceneName: 'Song_01b',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Song_01b',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Song_01',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Song_01',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Song_01',
		id: 'Song Shard Barrel',
	},
	{
		sceneName: 'Song_01',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Song_01',
		id: 'rosary_string_small (1)',
	},
	{
		sceneName: 'Under_03b',
		id: 'Song Shard Under Chest',
	},
	{
		sceneName: 'Under_04',
		id: 'Song Shard Under Chest',
	},
	{
		sceneName: 'Under_03d',
		id: 'Hero Treadmill Rosaries Paid',
	},
	{
		sceneName: 'Under_03d',
		id: 'Understore Large Worker',
	},
	{
		sceneName: 'Under_08',
		id: 'Song Shard Under Chest',
	},
	{
		sceneName: 'Under_07',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Under_07c',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Under_07c',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Under_07c',
		id: 'Song Shard Under Chest (1)',
	},
	{
		sceneName: 'Ward_01',
		id: 'under_lift_large',
	},
	{
		sceneName: 'Ward_06',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Ward_06',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Under_17',
		id: 'Song Shard Under Chest',
	},
	{
		sceneName: 'Library_11b',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Library_11b',
		id: 'Song Shard Barrel (1)',
	},
	{
		sceneName: 'Library_11b',
		id: 'Song Shard Barrel',
	},
	{
		sceneName: 'Library_11b',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Library_11b',
		id: 'Shell Shard Fossil Tiny Egg (2)',
	},
	{
		sceneName: 'Library_11b',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Bone_East_LavaChallenge',
		id: 'Shell Shard Fossil Mid',
	},
	{
		sceneName: 'Slab_05',
		id: 'jail_gate_breakable (2)',
	},
	{
		sceneName: 'Slab_05',
		id: 'jail_gate_breakable (3)',
	},
	{
		sceneName: 'Slab_05',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Slab_05',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Slab_05',
		id: 'Shell Shard Fossil Tiny Front (1)',
	},
	{
		sceneName: 'Peak_01',
		id: 'Shell Shard Fossil Tiny Bumpy (1)',
	},
	{
		sceneName: 'Peak_01',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Peak_02',
		id: 'Mapper NPC',
	},
	{
		sceneName: 'Bellway_Peak',
		id: 'rosary_string_small_mixed',
	},
	{
		sceneName: 'Bellway_Peak',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Bellway_Peak',
		id: 'rosary_string_medium (1)',
	},
	{
		sceneName: 'Peak_07',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Peak_07',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Peak_07',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Peak_07',
		id: 'NPC',
	},
	{
		sceneName: 'Song_28',
		id: 'Toll_machine_silk_ration',
	},
	{
		sceneName: 'Song_26',
		id: 'Music Box Sequence - EDITED',
	},
	{
		sceneName: 'Song_15',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Song_15',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Song_15',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Song_09',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Song_09',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Song_09',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Song_10',
		id: 'Shower Lever 2',
	},
	{
		sceneName: 'Song_10',
		id: 'Shower Lever',
	},
	{
		sceneName: 'Song_03',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Song_03',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Song_04',
		id: 'Green Prince Stand Song_04',
	},
	{
		sceneName: 'Greymoor_11',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Greymoor_11',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Bellshrine_03',
		id: 'Bellshrine Sequence',
	},
	{
		sceneName: 'Coral_02',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Coral_02',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Coral_02',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Coral_12',
		id: 'Mapper NPC (1)',
	},
	{
		sceneName: 'Song_Enclave',
		id: 'Enclave Simple NPC Tall',
	},
	{
		sceneName: 'Song_Enclave',
		id: 'Enclave Pilgrim Small',
	},
	{
		sceneName: 'Song_Enclave',
		id: 'Enclave Simple NPC Short Horned',
	},
	{
		sceneName: 'Song_Enclave',
		id: 'Sherma Healer',
	},
	{
		sceneName: 'Song_Enclave',
		id: 'Garmond Sleep NPC',
	},
	{
		sceneName: 'Song_Enclave',
		id: 'Enclave Simple NPC Standard',
	},
	{
		sceneName: 'Song_Enclave',
		id: 'Enclave Simple NPC Large',
	},
	{
		sceneName: 'Library_01',
		id: 'Library Sliding Plat',
	},
	{
		sceneName: 'Library_01',
		id: 'Library Sliding Plat (1)',
	},
	{
		sceneName: 'Library_04',
		id: 'rosary_bucket_library',
	},
	{
		sceneName: 'Library_04',
		id: 'Library Sliding Plat (2)',
	},
	{
		sceneName: 'Library_04',
		id: 'Library Sliding Plat (3)',
	},
	{
		sceneName: 'Library_04',
		id: 'Library Sliding Plat Tall (1)',
	},
	{
		sceneName: 'Library_04',
		id: 'Library Sliding Plat (1)',
	},
	{
		sceneName: 'Library_04',
		id: 'Library Sliding Plat',
	},
	{
		sceneName: 'Library_08',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Library_08',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Arborium_06',
		id: 'Shell Shard Fossil Coral Conch (1)',
	},
	{
		sceneName: 'Arborium_06',
		id: 'Shell Shard Fossil Coral Conch',
	},
	{
		sceneName: 'Arborium_10',
		id: 'Music Box Sequence - EDITED',
	},
	{
		sceneName: 'Room_Pinstress',
		id: 'Pinstress Interior Sit NPC',
	},
	{
		sceneName: 'Coral_24',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Coral_24',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Coral_40',
		id: 'Shell Shard Fossil Coral Conch (1)',
	},
	{
		sceneName: 'Coral_40',
		id: 'Shell Shard Fossil Coral Conch',
	},
	{
		sceneName: 'Coral_38',
		id: 'Shell Fossil Mimic',
	},
	{
		sceneName: 'Coral_38',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Coral_38',
		id: 'Hornet_cage_rect_lift',
	},
	{
		sceneName: 'Coral_38',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Coral_38',
		id: 'Shell Shard Fossil Tiny Front (2)',
	},
	{
		sceneName: 'Coral_38',
		id: 'Shell Shard Fossil Tiny Front (1)',
	},
	{
		sceneName: 'Coral_27',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Coral_27',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Coral_41',
		id: 'Shell Shard Fossil Coral Conch',
	},
	{
		sceneName: 'Dock_02',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Dock_02',
		id: 'rosary_string_small_half (2)',
	},
	{
		sceneName: 'Dock_02',
		id: 'Song Shard Barrel',
	},
	{
		sceneName: 'Dock_02b',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Dock_02b',
		id: 'Song Shard Barrel',
	},
	{
		sceneName: 'Dock_02b',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Dock_02b',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Hang_15',
		id: 'Song Shard Under Chest',
	},
	{
		sceneName: 'Hang_09',
		id: 'Song Shard Under Chest',
	},
	{
		sceneName: 'Library_05',
		id: 'Library Sliding Plat Tall',
	},
	{
		sceneName: 'Library_06',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Library_06',
		id: 'rosary_bucket_library',
	},
	{
		sceneName: 'Library_06',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Library_06',
		id: 'Library Sliding Plat',
	},
	{
		sceneName: 'Library_06',
		id: 'Library Sliding Plat (2)',
	},
	{
		sceneName: 'Library_06',
		id: 'Library Sliding Plat (3)',
	},
	{
		sceneName: 'Library_16',
		id: 'Music Box Sequence - EDITED',
	},
	{
		sceneName: 'Library_12b',
		id: 'Song Shard Under Chest',
	},
	{
		sceneName: 'Library_10',
		id: 'Library Statue NPC',
	},
	{
		sceneName: 'Hang_06_bank',
		id: 'rosary_string_large_mixed Variant',
	},
	{
		sceneName: 'Hang_06_bank',
		id: 'rosary_string_large_full Variant',
	},
	{
		sceneName: 'Hang_06_bank',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Hang_06_bank',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Hang_06_bank',
		id: 'rosary_string_small_half (1)',
	},
	{
		sceneName: 'Hang_06_bank',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Aqueduct_01',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Aqueduct_01',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Aqueduct_04',
		id: 'Shell Shard Fossil Tiny Egg (2)',
	},
	{
		sceneName: 'Aqueduct_04',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Aqueduct_04',
		id: 'Shell Shard Fossil Tiny Egg (1)',
	},
	{
		sceneName: 'Aqueduct_04',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Aqueduct_04',
		id: 'Shell Shard Fossil Tiny Front (1)',
	},
	{
		sceneName: 'Aqueduct_05',
		id: 'Shell Shard Fossil Dustpen Short',
	},
	{
		sceneName: 'Aqueduct_05',
		id: 'Shell Shard Fossil Dustpen Tall',
	},
	{
		sceneName: 'Aqueduct_05',
		id: 'Shell Shard Fossil Dustpen Tall (2)',
	},
	{
		sceneName: 'Aqueduct_05',
		id: 'Shell Shard Fossil Dustpen Tall (1)',
	},
	{
		sceneName: 'Aqueduct_05',
		id: 'Caravan Troup Member Tall - Act 2',
	},
	{
		sceneName: 'Aqueduct_05',
		id: 'Caravan Troup Member Tall - Act 3',
	},
	{
		sceneName: 'Aqueduct_05',
		id: 'Caravan Troup Member Short Fleatopia',
	},
	{
		sceneName: 'Aqueduct_05',
		id: 'Seth Sit NPC Fleatopia',
	},
	{
		sceneName: 'Slab_12',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Slab_12',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Slab_Cell_Creature',
		id: 'Slab Prisoner',
	},
	{
		sceneName: 'Slab_20',
		id: 'Thief NPC Slab Saferoom',
	},
	{
		sceneName: 'Slab_18',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Slab_18',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Slab_18',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Slab_19b',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Slab_19b',
		id: 'rosary_string_small (1)',
	},
	{
		sceneName: 'Slab_19b',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Slab_19b',
		id: 'rosary_string_medium',
	},
	{
		sceneName: 'Cradle_03',
		id: 'Shell Shard Fossil Mid Variant',
	},
	{
		sceneName: 'Dock_10',
		id: 'Forge Worker Sauna NPC',
	},
	{
		sceneName: 'Wisp_09',
		id: 'Shell Shard Fossil Tiny Bumpy (1)',
	},
	{
		sceneName: 'Wisp_09',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Wisp_09',
		id: 'Shell Shard Fossil Tiny Egg (1)',
	},
	{
		sceneName: 'Wisp_09',
		id: 'Shell Shard Fossil Tiny Egg (2)',
	},
	{
		sceneName: 'Wisp_09',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Wisp_09',
		id: 'Shell Shard Fossil Tiny Egg (3)',
	},
	{
		sceneName: 'Wisp_09',
		id: 'Shell Shard Fossil Mid Variant',
	},
	{
		sceneName: 'Under_23',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Library_07',
		id: 'rosary_cache_bell_ground',
	},
	{
		sceneName: 'Library_07',
		id: 'Song Shard Under Chest',
	},
	{
		sceneName: 'Shadow_23',
		id: 'Rosary Pilgrim',
	},
	{
		sceneName: 'Shadow_05',
		id: 'rosary_string_small_half',
	},
	{
		sceneName: 'Shadow_11',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Shadow_11',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Shadow_10',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Shadow_10',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Shadow_25',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Shadow_25',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Shadow_25',
		id: 'Shell Shard Fossil Mid Variant',
	},
	{
		sceneName: 'Shellwood_25',
		id: 'Shell Shard Fossil Tiny Egg (1)',
	},
	{
		sceneName: 'Mosstown_03',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Mosstown_03',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Mosstown_03',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Dust_Shack',
		id: 'Dust Traders',
	},
	{
		sceneName: 'Cog_10_Destroyed',
		id: 'jail_gate_breakable',
	},
	{
		sceneName: 'Tut_04',
		id: 'Snail Shamans Set',
	},
	{
		sceneName: 'Abyss_03',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Abyss_03',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Abyss_03',
		id: 'Shell Shard Fossil Tiny Front (1)',
	},
	{
		sceneName: 'Abyss_03',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Abyss_05',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Abyss_05',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Abyss_05',
		id: 'Shell Shard Fossil Tiny Egg (1)',
	},
	{
		sceneName: 'Abyss_05',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Abyss_05',
		id: 'Shell Shard Fossil Mid Variant',
	},
	{
		sceneName: 'Abyss_08',
		id: 'Inspect Region - Void Tendrils',
	},
	{
		sceneName: 'Dock_12',
		id: 'Ballow Diving Bell Repair NPC',
	},
	{
		sceneName: 'Bone_East_24',
		id: 'ant_rosary_string (1)',
	},
	{
		sceneName: 'Bone_East_24',
		id: 'ant_item_string',
	},
	{
		sceneName: 'Bone_East_24',
		id: 'Shell Shard Fossil Tiny Bumpy',
	},
	{
		sceneName: 'Bone_East_24',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Bone_East_24',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Bone_East_24',
		id: 'Shell Shard Fossil Mid Variant',
	},
	{
		sceneName: 'Bone_East_24',
		id: 'ant_rosary_string_large',
	},
	{
		sceneName: 'Bone_East_18',
		id: 'ant_rosary_string',
	},
	{
		sceneName: 'Bone_East_18',
		id: 'ant_shell_shard_string',
	},
	{
		sceneName: 'Bone_East_18',
		id: 'ant_shell_shard_string (1)',
	},
	{
		sceneName: 'Bone_East_18b',
		id: 'ant_item_string',
	},
	{
		sceneName: 'Sprintmaster_Cave',
		id: 'Sprintmaster Runner',
	},
	{
		sceneName: 'Ant_Queen',
		id: 'Ant Queen BG NPC',
	},
	{
		sceneName: 'Bone_East_09b',
		id: 'ant_rosary_string',
	},
	{
		sceneName: 'Bone_East_09b',
		id: 'ant_rosary_string (1)',
	},
	{
		sceneName: 'Peak_06',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Peak_06',
		id: 'Shell Shard Fossil Tiny Front',
	},
	{
		sceneName: 'Under_27',
		id: 'Song Shard Barrel',
	},
	{
		sceneName: 'Bellway_Peak_02',
		id: 'rosary_cache_hang',
	},
	{
		sceneName: 'Room_CrowCourt_02',
		id: 'rosary_string_small_half (2)',
	},
	{
		sceneName: 'Room_CrowCourt_02',
		id: 'rosary_string_small_half (3)',
	},
	{
		sceneName: 'Room_CrowCourt_02',
		id: 'rosary_string_small',
	},
	{
		sceneName: 'Coral_36',
		id: 'Shell Shard Fossil Tiny Egg',
	},
	{
		sceneName: 'Coral_36',
		id: 'Shell Shard Fossil Beast',
	},
];
export type SceneDataIntSilk = (typeof list)[number];
export const sceneDataIntSilk = {
	list,
	byName: Object.fromEntries(list.map((it: any) => [it.id, it])) as Record<SceneDataIntNameSilk, SceneDataIntSilk>,
};

export const sceneDataIntIdToNameSilk: Map<number, SceneDataIntNameSilk> = new Map([
	[1, 'Shell Shard Fossil Large Uni'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[5, 'Shell Shard Fossil Mid (1)'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[6, 'Churchkeeper Basement'],
	[7, 'rosary_string_small_half'],
	[8, 'rosary_shrine_small'],
	[9, 'rosary_string_medium'],
	[10, 'Churchkeeper'],
	[11, 'Fixer Pilgrim Bench Repair'],
	[12, 'Fixer Pilgrim'],
	[13, 'Fixer NPC Standing'],
	[14, 'Mapper NPC'],
	[15, 'Generic Pilgrim Round'],
	[16, 'Generic Pilgrim Stomper'],
	[17, 'Shell Shard Fossil Big'],
	[18, 'Bellway Pilgrim'],
	[19, 'rosary_string_small_half (2)'],
	[20, 'rosary_string_small'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[21, 'rosary_string_small_half (1)'],
	[9, 'rosary_string_medium'],
	[22, 'Shell Shard Fossil Tiny Front (2)'],
	[23, 'Shell Shard Fossil Tiny Front (3)'],
	[14, 'Mapper NPC'],
	[24, 'rosary_string_small_mixed'],
	[20, 'rosary_string_small'],
	[8, 'rosary_shrine_small'],
	[25, 'Caravan Troup Member Tall'],
	[26, 'Caravan Troup Member Short'],
	[27, 'Fixer Sitting Bone_10'],
	[28, 'rosary_string_small (1)'],
	[29, 'rosary_string_small (2)'],
	[7, 'rosary_string_small_half'],
	[8, 'rosary_shrine_small'],
	[20, 'rosary_string_small'],
	[20, 'rosary_string_small'],
	[7, 'rosary_string_small_half'],
	[30, 'Bellshrine Sequence'],
	[31, 'Shell Fossil Mimic AppearVariant'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[32, 'Shell Fossil Mimic'],
	[1, 'Shell Shard Fossil Large Uni'],
	[21, 'rosary_string_small_half (1)'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[33, 'rosary_cache_hang_bell'],
	[34, 'rosary_cache_bell_ground (1)'],
	[35, 'rosary_cache_bell_ground'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[36, 'Thief NPC Saved'],
	[37, 'Pin Challenge'],
	[38, 'Song Shard Barrel'],
	[14, 'Mapper NPC'],
	[38, 'Song Shard Barrel'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[28, 'rosary_string_small (1)'],
	[21, 'rosary_string_small_half (1)'],
	[39, 'Shell Shard Fossil Dock (2)'],
	[40, 'Shell Shard Fossil Dock (1)'],
	[41, 'Shell Shard Fossil Dock (3)'],
	[32, 'Shell Fossil Mimic'],
	[8, 'rosary_shrine_small'],
	[30, 'Bellshrine Sequence'],
	[42, 'Shell Shard Fossil Mid'],
	[7, 'rosary_string_small_half'],
	[43, 'ant_rosary_string (2)'],
	[44, 'ant_rosary_string'],
	[45, 'ant_rosary_string (1)'],
	[44, 'ant_rosary_string'],
	[45, 'ant_rosary_string (1)'],
	[44, 'ant_rosary_string'],
	[45, 'ant_rosary_string (1)'],
	[46, 'Sherma Docks NPC'],
	[47, 'Generic Pilgrim Large'],
	[20, 'rosary_string_small'],
	[9, 'rosary_string_medium'],
	[32, 'Shell Fossil Mimic'],
	[20, 'rosary_string_small'],
	[7, 'rosary_string_small_half'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[48, 'Seth Sit NPC Greymoor'],
	[7, 'rosary_string_small_half'],
	[49, 'Hornet_cage_rect_lift_greymoor'],
	[20, 'rosary_string_small'],
	[19, 'rosary_string_small_half (2)'],
	[50, 'rosary_string_small_half (3)'],
	[21, 'rosary_string_small_half (1)'],
	[20, 'rosary_string_small'],
	[51, 'rosary_string_small_half (6)'],
	[52, 'rosary_string_small_half (8)'],
	[53, 'rosary_string_small_half (7)'],
	[21, 'rosary_string_small_half (1)'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[9, 'rosary_string_medium'],
	[54, 'HH Bartender'],
	[55, 'HH Patron Right'],
	[56, 'HH Patron Left'],
	[7, 'rosary_string_small_half'],
	[21, 'rosary_string_small_half (1)'],
	[57, 'Garmond Sleep NPC'],
	[21, 'rosary_string_small_half (1)'],
	[8, 'rosary_shrine_small'],
	[20, 'rosary_string_small'],
	[58, 'scissor_string (7)'],
	[59, 'scissor_string (4)'],
	[60, 'scissor_string (6)'],
	[61, 'scissor_string (5)'],
	[59, 'scissor_string (4)'],
	[62, 'scissor_string (2)'],
	[58, 'scissor_string (7)'],
	[63, 'scissor_string (8)'],
	[64, 'scissor_string (9)'],
	[61, 'scissor_string (5)'],
	[60, 'scissor_string (6)'],
	[65, 'scissor_string (1)'],
	[7, 'rosary_string_small_half'],
	[66, 'Mapper StandGuard NPC'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[9, 'rosary_string_medium'],
	[67, 'Shell Shard Fossil Tiny Egg (1)'],
	[45, 'ant_rosary_string (1)'],
	[68, 'ant_item_string'],
	[44, 'ant_rosary_string'],
	[14, 'Mapper NPC'],
	[69, 'ant_shell_shard_string (2)'],
	[70, 'ant_shell_shard_string (1)'],
	[71, 'ant_shell_shard_string'],
	[69, 'ant_shell_shard_string (2)'],
	[70, 'ant_shell_shard_string (1)'],
	[72, 'ant_shell_shard_string (3)'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[30, 'Bellshrine Sequence'],
	[73, 'Pilgrim Fisher NPC Walker'],
	[74, 'Courier Short Bellhart'],
	[75, 'Belltown Greeter Act3'],
	[14, 'Mapper NPC'],
	[33, 'rosary_cache_hang_bell'],
	[76, 'Shell Shard Fossil Tiny Bumpy (1)'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[66, 'Mapper StandGuard NPC'],
	[77, 'Hornet_cage_rect_lift'],
	[77, 'Hornet_cage_rect_lift'],
	[14, 'Mapper NPC'],
	[78, 'Rosary Pilgrim'],
	[14, 'Mapper NPC'],
	[25, 'Caravan Troup Member Tall'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[79, 'Shell Shard Fossil Tiny Bumpy (2)'],
	[76, 'Shell Shard Fossil Tiny Bumpy (1)'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[42, 'Shell Shard Fossil Mid'],
	[35, 'rosary_cache_bell_ground'],
	[20, 'rosary_string_small'],
	[9, 'rosary_string_medium'],
	[80, 'Bellshrine Sequence Bellhart'],
	[44, 'ant_rosary_string'],
	[81, 'ant_rosary_string (3)'],
	[82, 'ant_rosary_string_medium'],
	[83, 'ant_rosary_string_medium (1)'],
	[84, 'ant_rosary_string_medium (2)'],
	[85, 'ant_rosary_string_medium (3)'],
	[86, 'ant_rosary_string_medium Variant'],
	[87, 'ant_rosary_string_large (1)'],
	[88, 'ant_rosary_string_large'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[89, 'rosary_string_small_half (4)'],
	[90, 'rosary_string_small_half (5)'],
	[21, 'rosary_string_small_half (1)'],
	[9, 'rosary_string_medium'],
	[91, 'Courier Short'],
	[92, 'NPC'],
	[93, 'Green Prince Sit'],
	[7, 'rosary_string_small_half'],
	[21, 'rosary_string_small_half (1)'],
	[76, 'Shell Shard Fossil Tiny Bumpy (1)'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[94, 'Courier Tall'],
	[7, 'rosary_string_small_half'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[9, 'rosary_string_medium'],
	[95, 'Hornet_cage_rect_lift_organ (1)'],
	[96, 'Shell Shard Fossil Dustpen Short'],
	[97, 'Shell Shard Fossil Dustpen Tall'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[98, 'library_lift_large'],
	[38, 'Song Shard Barrel'],
	[99, 'Library Sliding Plat (1)'],
	[100, 'Library Sliding Plat (5)'],
	[101, 'Library Sliding Plat (2)'],
	[102, 'Library Sliding Plat'],
	[103, 'Library Sliding Plat Tall (1)'],
	[104, 'Library Sliding Plat Tall (2)'],
	[105, 'Library Sliding Plat Tall'],
	[106, 'Toll_machine_silk_ration'],
	[101, 'Library Sliding Plat (2)'],
	[99, 'Library Sliding Plat (1)'],
	[30, 'Bellshrine Sequence'],
	[21, 'rosary_string_small_half (1)'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[9, 'rosary_string_medium'],
	[24, 'rosary_string_small_mixed'],
	[20, 'rosary_string_small'],
	[9, 'rosary_string_medium'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[38, 'Song Shard Barrel'],
	[9, 'rosary_string_medium'],
	[28, 'rosary_string_small (1)'],
	[107, 'Song Shard Under Chest'],
	[107, 'Song Shard Under Chest'],
	[108, 'Hero Treadmill Rosaries Paid'],
	[109, 'Understore Large Worker'],
	[107, 'Song Shard Under Chest'],
	[7, 'rosary_string_small_half'],
	[7, 'rosary_string_small_half'],
	[21, 'rosary_string_small_half (1)'],
	[110, 'Song Shard Under Chest (1)'],
	[111, 'under_lift_large'],
	[7, 'rosary_string_small_half'],
	[9, 'rosary_string_medium'],
	[107, 'Song Shard Under Chest'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[112, 'Song Shard Barrel (1)'],
	[38, 'Song Shard Barrel'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[113, 'Shell Shard Fossil Tiny Egg (2)'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[42, 'Shell Shard Fossil Mid'],
	[114, 'jail_gate_breakable (2)'],
	[115, 'jail_gate_breakable (3)'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[116, 'Shell Shard Fossil Tiny Front (1)'],
	[76, 'Shell Shard Fossil Tiny Bumpy (1)'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[14, 'Mapper NPC'],
	[24, 'rosary_string_small_mixed'],
	[9, 'rosary_string_medium'],
	[117, 'rosary_string_medium (1)'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[92, 'NPC'],
	[106, 'Toll_machine_silk_ration'],
	[118, 'Music Box Sequence - EDITED'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[9, 'rosary_string_medium'],
	[21, 'rosary_string_small_half (1)'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[119, 'Shower Lever 2'],
	[120, 'Shower Lever'],
	[21, 'rosary_string_small_half (1)'],
	[20, 'rosary_string_small'],
	[121, 'Green Prince Stand Song_04'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[30, 'Bellshrine Sequence'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[122, 'Mapper NPC (1)'],
	[123, 'Enclave Simple NPC Tall'],
	[124, 'Enclave Pilgrim Small'],
	[125, 'Enclave Simple NPC Short Horned'],
	[126, 'Sherma Healer'],
	[57, 'Garmond Sleep NPC'],
	[127, 'Enclave Simple NPC Standard'],
	[128, 'Enclave Simple NPC Large'],
	[102, 'Library Sliding Plat'],
	[99, 'Library Sliding Plat (1)'],
	[129, 'rosary_bucket_library'],
	[101, 'Library Sliding Plat (2)'],
	[130, 'Library Sliding Plat (3)'],
	[103, 'Library Sliding Plat Tall (1)'],
	[99, 'Library Sliding Plat (1)'],
	[102, 'Library Sliding Plat'],
	[7, 'rosary_string_small_half'],
	[20, 'rosary_string_small'],
	[131, 'Shell Shard Fossil Coral Conch (1)'],
	[132, 'Shell Shard Fossil Coral Conch'],
	[118, 'Music Box Sequence - EDITED'],
	[133, 'Pinstress Interior Sit NPC'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[131, 'Shell Shard Fossil Coral Conch (1)'],
	[132, 'Shell Shard Fossil Coral Conch'],
	[32, 'Shell Fossil Mimic'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[77, 'Hornet_cage_rect_lift'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[22, 'Shell Shard Fossil Tiny Front (2)'],
	[116, 'Shell Shard Fossil Tiny Front (1)'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[132, 'Shell Shard Fossil Coral Conch'],
	[21, 'rosary_string_small_half (1)'],
	[19, 'rosary_string_small_half (2)'],
	[38, 'Song Shard Barrel'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[38, 'Song Shard Barrel'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[107, 'Song Shard Under Chest'],
	[107, 'Song Shard Under Chest'],
	[105, 'Library Sliding Plat Tall'],
	[7, 'rosary_string_small_half'],
	[129, 'rosary_bucket_library'],
	[20, 'rosary_string_small'],
	[102, 'Library Sliding Plat'],
	[101, 'Library Sliding Plat (2)'],
	[130, 'Library Sliding Plat (3)'],
	[118, 'Music Box Sequence - EDITED'],
	[107, 'Song Shard Under Chest'],
	[134, 'Library Statue NPC'],
	[135, 'rosary_string_large_mixed Variant'],
	[136, 'rosary_string_large_full Variant'],
	[9, 'rosary_string_medium'],
	[20, 'rosary_string_small'],
	[21, 'rosary_string_small_half (1)'],
	[7, 'rosary_string_small_half'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[113, 'Shell Shard Fossil Tiny Egg (2)'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[67, 'Shell Shard Fossil Tiny Egg (1)'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[116, 'Shell Shard Fossil Tiny Front (1)'],
	[96, 'Shell Shard Fossil Dustpen Short'],
	[97, 'Shell Shard Fossil Dustpen Tall'],
	[137, 'Shell Shard Fossil Dustpen Tall (2)'],
	[138, 'Shell Shard Fossil Dustpen Tall (1)'],
	[139, 'Caravan Troup Member Tall - Act 2'],
	[140, 'Caravan Troup Member Tall - Act 3'],
	[141, 'Caravan Troup Member Short Fleatopia'],
	[142, 'Seth Sit NPC Fleatopia'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[143, 'Slab Prisoner'],
	[144, 'Thief NPC Slab Saferoom'],
	[7, 'rosary_string_small_half'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[7, 'rosary_string_small_half'],
	[28, 'rosary_string_small (1)'],
	[20, 'rosary_string_small'],
	[9, 'rosary_string_medium'],
	[145, 'Shell Shard Fossil Mid Variant'],
	[146, 'Forge Worker Sauna NPC'],
	[76, 'Shell Shard Fossil Tiny Bumpy (1)'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[67, 'Shell Shard Fossil Tiny Egg (1)'],
	[113, 'Shell Shard Fossil Tiny Egg (2)'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[147, 'Shell Shard Fossil Tiny Egg (3)'],
	[145, 'Shell Shard Fossil Mid Variant'],
	[7, 'rosary_string_small_half'],
	[35, 'rosary_cache_bell_ground'],
	[107, 'Song Shard Under Chest'],
	[78, 'Rosary Pilgrim'],
	[7, 'rosary_string_small_half'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[145, 'Shell Shard Fossil Mid Variant'],
	[67, 'Shell Shard Fossil Tiny Egg (1)'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[148, 'Dust Traders'],
	[149, 'jail_gate_breakable'],
	[150, 'Snail Shamans Set'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[116, 'Shell Shard Fossil Tiny Front (1)'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[67, 'Shell Shard Fossil Tiny Egg (1)'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[145, 'Shell Shard Fossil Mid Variant'],
	[151, 'Inspect Region - Void Tendrils'],
	[152, 'Ballow Diving Bell Repair NPC'],
	[45, 'ant_rosary_string (1)'],
	[68, 'ant_item_string'],
	[2, 'Shell Shard Fossil Tiny Bumpy'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[145, 'Shell Shard Fossil Mid Variant'],
	[88, 'ant_rosary_string_large'],
	[44, 'ant_rosary_string'],
	[71, 'ant_shell_shard_string'],
	[70, 'ant_shell_shard_string (1)'],
	[68, 'ant_item_string'],
	[153, 'Sprintmaster Runner'],
	[154, 'Ant Queen BG NPC'],
	[44, 'ant_rosary_string'],
	[45, 'ant_rosary_string (1)'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[4, 'Shell Shard Fossil Tiny Front'],
	[38, 'Song Shard Barrel'],
	[155, 'rosary_cache_hang'],
	[19, 'rosary_string_small_half (2)'],
	[50, 'rosary_string_small_half (3)'],
	[20, 'rosary_string_small'],
	[3, 'Shell Shard Fossil Tiny Egg'],
	[156, 'Shell Shard Fossil Beast'],
]);
export const sceneDataIntNamesSilk: SceneDataIntNameSilk[] = sceneDataIntIdToNameSilk.values().toArray();
