import * as v from 'valibot';

export const silkMapZoneSchema = v.picklist([
	'NONE',
	'TEST_AREA',
	'PATH_OF_BONE',
	'GREYMOOR',
	'SHELLWOOD_THICKET',
	'RED_CORAL_GORGE',
	'CITY_OF_SONG',
	'THE_SLAB',
	'GLOOM',
	'DUSTPENS',
	'BELLTOWN',
	'HUNTERS_NEST',
	'BONETOWN',
	'MOSS_CAVE',
	'PHARLOOM_BAY',
	'DOCKS',
	'WILDS',
	'WEAVER_SHRINE',
	'BONECHURCH',
	'MOSSTOWN',
	'LIBRARY',
	'CLOVER',
	'UNDERSTORE',
	'COG_CORE',
	'PEAK',
	'DUST_MAZE',
	'WARD',
	'HANG',
	'ARBORIUM',
	'CRADLE',
	'PILGRIMS_REST',
	'HALFWAY_HOUSE',
	'JUDGE_STEPS',
	'MEMORY',
	'CRAWLSPACE',
	'WISP',
	'SWAMP',
	'ABYSS',
	'AQUEDUCT',
	'SURFACE',
	'FRONT_GATE',
	'CORAL_CAVERNS',
]);

export type SilkMapZone = v.InferOutput<typeof silkMapZoneSchema>;
