/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
export const silksongVersionSilk = { all: [{ id: '1.0.30000' }] };
export type SilksongVersionNameSilk = '1.0.30000';

export const silksongVersionIdToNameSilk: Map<number, SilksongVersionNameSilk> = new Map([[1, '1.0.30000']]);
export const silksongVersionNamesSilk: SilksongVersionNameSilk[] = silksongVersionIdToNameSilk.values().toArray();
