/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */

export type SilksongVersionNameSilk = '1.0.30000';

const list = [
	{
		id: '1.0.30000',
	},
];
export type SilksongVersionSilk = (typeof list)[number];
export const silksongVersionSilk = {
	list,
	byName: Object.fromEntries(list.map((it: any) => [it.id, it])) as Record<
		SilksongVersionNameSilk,
		SilksongVersionSilk
	>,
};

export const silksongVersionIdToNameSilk: Map<number, SilksongVersionNameSilk> = new Map([[1, '1.0.30000']]);
export const silksongVersionNamesSilk: SilksongVersionNameSilk[] = silksongVersionIdToNameSilk.values().toArray();
