/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
export const toolLiquidSilk = { all: [{ id: 'Flea Brew' }, { id: 'Lifeblood Syringe' }] };
export type ToolLiquidNameSilk = 'Flea Brew' | 'Lifeblood Syringe';

export const toolLiquidIdToNameSilk: Map<number, ToolLiquidNameSilk> = new Map([
	[1, 'Flea Brew'],
	[2, 'Lifeblood Syringe'],
]);
export const toolLiquidNamesSilk: ToolLiquidNameSilk[] = toolLiquidIdToNameSilk.values().toArray();
