/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
export const toolItemSilk = {
	all: [
		{
			id: 'Silk Spear',
			displayName: 'UI.INV_NAME_SKILL_THROW',
			type: 'Skill',
			toolSprite: {
				name: 'S_needle_throw_10_133x123_5',
				nameShort: 'S_needle_throw',
				size: {
					x: 133.0,
					y: 123.0,
				},
				padding: {
					x: 0.0267509818,
					y: 12.0267506,
					z: 0.0,
					w: 11.0362854,
				},
			},
			alternateUnlockedTest: {
				playerDataOverrideType: null,
				testGroups: [
					{
						tests: [
							{
								type: 'Bool',
								fieldName: 'hasNeedleThrow',
								boolValue: true,
								numType: null,
								intValue: null,
								floatValue: null,
								stringValue: null,
								stringType: null,
							},
						],
					},
				],
			},
		},
		{
			id: 'Thread Sphere',
			displayName: 'UI.INV_NAME_SKILL_SPHERE',
			type: 'Skill',
			toolSprite: {
				name: 'S_thread_sphere_40_112x113_5',
				nameShort: 'S_thread_sphere',
				size: {
					x: 112.0,
					y: 113.0,
				},
				padding: {
					x: 1.03628516,
					y: 4.05131674,
					z: 1.04290771,
					w: 1.07611847,
				},
			},
			alternateUnlockedTest: {
				playerDataOverrideType: null,
				testGroups: [
					{
						tests: [
							{
								type: 'Bool',
								fieldName: 'hasThreadSphere',
								boolValue: true,
								numType: null,
								intValue: null,
								floatValue: null,
								stringValue: null,
								stringType: null,
							},
						],
					},
				],
			},
		},
		{
			id: 'Parry',
			displayName: 'UI.INV_NAME_SKILL_PARRY',
			type: 'Skill',
			toolSprite: {
				name: 'S_parry_18_120x116_2',
				nameShort: 'S_parry',
				size: {
					x: 120.0,
					y: 116.0,
				},
				padding: {
					x: 1.0761205,
					y: 2.01291251,
					z: 1.07611847,
					w: 9.076118,
				},
			},
			alternateUnlockedTest: {
				playerDataOverrideType: null,
				testGroups: [
					{
						tests: [
							{
								type: 'Bool',
								fieldName: 'hasParry',
								boolValue: true,
								numType: null,
								intValue: null,
								floatValue: null,
								stringValue: null,
								stringType: null,
							},
						],
					},
				],
			},
		},
		{
			id: 'Silk Charge',
			displayName: 'UI.INV_NAME_SKILL_SILKDASH',
			type: 'Skill',
			toolSprite: {
				name: 'S_thread_dash_15_117x120_2',
				nameShort: 'S_thread_dash',
				size: {
					x: 117.0,
					y: 120.0,
				},
				padding: {
					x: 1.05412674,
					y: 2.05131674,
					z: 2.02674866,
					w: 2.05131531,
				},
			},
			alternateUnlockedTest: {
				playerDataOverrideType: null,
				testGroups: [
					{
						tests: [
							{
								type: 'Bool',
								fieldName: 'hasSilkCharge',
								boolValue: true,
								numType: null,
								intValue: null,
								floatValue: null,
								stringValue: null,
								stringType: null,
							},
						],
					},
				],
			},
		},
		{
			id: 'Silk Bomb',
			displayName: 'UI.INV_NAME_SKILL_SILKBOMB',
			type: 'Skill',
			toolSprite: {
				name: 'S_bomb_33_124x113_2',
				nameShort: 'S_bomb',
				size: {
					x: 124.0,
					y: 113.0,
				},
				padding: {
					x: 3.05972838,
					y: 6.07612038,
					z: 3.03796387,
					w: 6.07611847,
				},
			},
			alternateUnlockedTest: {
				playerDataOverrideType: null,
				testGroups: [
					{
						tests: [
							{
								type: 'Bool',
								fieldName: 'hasSilkBomb',
								boolValue: true,
								numType: null,
								intValue: null,
								floatValue: null,
								stringValue: null,
								stringType: null,
							},
						],
					},
				],
			},
		},
		{
			id: 'Silk Boss Needle',
			displayName: 'UI.INV_NAME_SKILL_SILKBOSS_NEEDLE',
			type: 'Skill',
			toolSprite: {
				name: 'S_finger_blade_28_119x128_8',
				nameShort: 'S_finger_blade',
				size: {
					x: 119.0,
					y: 128.0,
				},
				padding: {
					x: 3.07612038,
					y: 6.01291275,
					z: 2.0477066,
					w: 1.02674866,
				},
			},
			alternateUnlockedTest: {
				playerDataOverrideType: null,
				testGroups: [
					{
						tests: [
							{
								type: 'Bool',
								fieldName: 'hasSilkBossNeedle',
								boolValue: true,
								numType: null,
								intValue: null,
								floatValue: null,
								stringValue: null,
								stringType: null,
							},
						],
					},
				],
			},
		},
		{
			id: 'Straight Pin',
			displayName: 'Tools.STRAIGHT_PIN_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_straight_pin_9_120x120_0',
				nameShort: 'T_straight_pin',
				size: {
					x: 120.0,
					y: 120.0,
				},
				padding: {
					x: 0.0,
					y: 5.042908,
					z: 0.0,
					w: 9.076118,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Tri Pin',
			displayName: 'Tools.TRI_PIN_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_tri_pin_26_157x148_0',
				nameShort: 'T_tri_pin',
				size: {
					x: 157.0,
					y: 148.0,
				},
				padding: {
					x: 3.042908,
					y: 1.0761205,
					z: 11.0362854,
					w: 10.0761261,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Sting Shard',
			displayName: 'Tools.STING_SHARD_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_sting_shard_10_138x138_0',
				nameShort: 'T_sting_shard',
				size: {
					x: 138.0,
					y: 138.0,
				},
				padding: {
					x: 0.0761204958,
					y: 0.06389725,
					z: 0.0,
					w: 0.0761261,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Tack',
			displayName: 'Tools.TACK_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_tack_16_117x125_0',
				nameShort: 'T_tack',
				size: {
					x: 117.0,
					y: 125.0,
				},
				padding: {
					x: 0.0,
					y: 0.0,
					z: 0.0,
					w: 0.07611847,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Harpoon',
			displayName: 'Tools.HARPOON_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_claw_javelin_7_152x148_0',
				nameShort: 'T_claw_javelin',
				size: {
					x: 152.0,
					y: 148.0,
				},
				padding: {
					x: 3.026751,
					y: 4.03465557,
					z: 3.04290771,
					w: 5.076126,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Curve Claws',
			displayName: 'Tools.CURVE_CLAWS_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_curve_claw_9_154x144_0',
				nameShort: 'T_curve_claw',
				size: {
					x: 154.0,
					y: 144.0,
				},
				padding: {
					x: 15.07612,
					y: 6.05131674,
					z: 12.0761261,
					w: 9.042908,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Curve Claws Upgraded',
			displayName: 'Tools.CURVE_CLAWS_UPG_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_curve_claw_upgraded_14_129x119_1',
				nameShort: 'T_curve_claw_upgraded',
				size: {
					x: 129.0,
					y: 119.0,
				},
				padding: {
					x: 1.026751,
					y: 3.07612038,
					z: 1.02674866,
					w: 3.07611847,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Shakra Ring',
			displayName: 'Tools.SHAKRA_RING_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_shakra_ring_9_120x120_0',
				nameShort: 'T_shakra_ring',
				size: {
					x: 120.0,
					y: 120.0,
				},
				padding: {
					x: 6.07612038,
					y: 3.07612038,
					z: 6.07611847,
					w: 7.07611847,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Pimpilo',
			displayName: 'Tools.PIMPILO_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_pimpilo_12_120x120_0',
				nameShort: 'T_pimpilo',
				size: {
					x: 120.0,
					y: 120.0,
				},
				padding: {
					x: 2.042908,
					y: 2.07612038,
					z: 3.02674866,
					w: 5.04290771,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Conch Drill',
			displayName: 'Tools.CONCH_DRILL_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_Conch_Drill_Shot_8_122x116_0',
				nameShort: 'T_Conch_Drill_Shot',
				size: {
					x: 122.0,
					y: 116.0,
				},
				padding: {
					x: 1.026751,
					y: 1.0761205,
					z: 1.02674866,
					w: 0.07611847,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'WebShot Forge',
			displayName: 'Tools.SILKSHOT_NAME',
			type: 'Red',
			toolSprite: {
				name: '_0002_T_web_shot_forge_8_122x113_2',
				nameShort: '_0002_T_web_shot_forge',
				size: {
					x: 122.0,
					y: 113.0,
				},
				padding: {
					x: 0.0,
					y: 0.0,
					z: 0.0,
					w: 0.0,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'WebShot Architect',
			displayName: 'Tools.SILKSHOT_NAME',
			type: 'Red',
			toolSprite: {
				name: '_0003_T_web_shot_architect_9_122x114_1',
				nameShort: '_0003_T_web_shot_architect',
				size: {
					x: 122.0,
					y: 114.0,
				},
				padding: {
					x: 0.0,
					y: 0.0,
					z: 0.0,
					w: 0.0429077148,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'WebShot Weaver',
			displayName: 'Tools.SILKSHOT_NAME',
			type: 'Red',
			toolSprite: {
				name: '_0001_T_web_shot_forge_runes_10_132x119_1',
				nameShort: '_0001_T_web_shot_forge_runes',
				size: {
					x: 132.0,
					y: 119.0,
				},
				padding: {
					x: 2.026751,
					y: 2.026751,
					z: 0.0761261,
					w: 9.026749,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Screw Attack',
			displayName: 'Tools.SCREWATTACK_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_Spine_head_14_130x129_2',
				nameShort: 'T_Spine_head',
				size: {
					x: 130.0,
					y: 129.0,
				},
				padding: {
					x: 6.04290771,
					y: 2.07612038,
					z: 2.02674866,
					w: 2.05131531,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Cogwork Saw',
			displayName: 'Tools.COGWORK_SAW_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_cogwork_saw_8_136x136_0',
				nameShort: 'T_cogwork_saw',
				size: {
					x: 136.0,
					y: 136.0,
				},
				padding: {
					x: 1.0761205,
					y: 1.0761205,
					z: 1.0761261,
					w: 2.02674866,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Cogwork Flier',
			displayName: 'Tools.COGWORK_FLIER_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_cogwork_flier_8_157x126_0',
				nameShort: 'T_cogwork_flier',
				size: {
					x: 157.0,
					y: 126.0,
				},
				padding: {
					x: 20.02675,
					y: 11.0477047,
					z: 0.0267486572,
					w: 0.07611847,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Rosary Cannon',
			displayName: 'Tools.ROSARYCANNON_NAME',
			type: 'Red',
			toolSprite: {
				name: '_0004_T_rosary_cannon_loaded_9_124x124_1',
				nameShort: '_0004_T_rosary_cannon_loaded',
				size: {
					x: 124.0,
					y: 124.0,
				},
				padding: {
					x: 0.0,
					y: 0.0,
					z: 0.0,
					w: 0.0,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Lightning Rod',
			displayName: 'Tools.LIGHTNING_ROD_NAME',
			type: 'Red',
			toolSprite: {
				name: '_0004_T_lightning__0001_1_9_138x148_1',
				nameShort: '_0004_T_lightning__0001_1',
				size: {
					x: 138.0,
					y: 148.0,
				},
				padding: {
					x: 0.0,
					y: 0.0,
					z: 0.0,
					w: 0.0,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Flintstone',
			displayName: 'Tools.FLINTSTONE_NAME',
			type: 'Red',
			toolSprite: {
				name: 'Hornet_icon_0003_T_flintstone_10_146x147_2',
				nameShort: 'Hornet_icon_0003_T_flintstone',
				size: {
					x: 146.0,
					y: 147.0,
				},
				padding: {
					x: 6.07612038,
					y: 9.026751,
					z: 1.02674866,
					w: 2.05131531,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Silk Snare',
			displayName: 'Tools.SNARE_NAME',
			type: 'Red',
			toolSprite: {
				name: '_0004_T_snare_setter_7_121x126_3',
				nameShort: '_0004_T_snare_setter',
				size: {
					x: 121.0,
					y: 126.0,
				},
				padding: {
					x: 4.05131674,
					y: 1.042908,
					z: 0.0513153076,
					w: 7.02674866,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Flea Brew',
			displayName: 'Tools.FLEA_BREW_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_flea_brew_19_115x140_1',
				nameShort: 'T_flea_brew',
				size: {
					x: 115.0,
					y: 140.0,
				},
				padding: {
					x: 7.026751,
					y: 7.026751,
					z: 4.012909,
					w: 7.076126,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Lifeblood Syringe',
			displayName: 'Tools.SYRINGE_LIFEBLOOD_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_syringe_lifeblood_8_139x138_0',
				nameShort: 'T_syringe_lifeblood',
				size: {
					x: 139.0,
					y: 138.0,
				},
				padding: {
					x: 0.0,
					y: 0.0,
					z: 1.0761261,
					w: 0.0,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Extractor',
			displayName: 'Tools.EXTRACTOR_NAME',
			type: 'Red',
			toolSprite: {
				name: 'T_Extractor_9_151x147_1',
				nameShort: 'T_Extractor',
				size: {
					x: 151.0,
					y: 147.0,
				},
				padding: {
					x: 11.07612,
					y: 0.0,
					z: 4.047699,
					w: 0.0761261,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Mosscreep Tool 1',
			displayName: 'Tools.MOSSCREEP_TOOL_1_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_mossmedal_12_124x124_0',
				nameShort: 'T_mossmedal',
				size: {
					x: 124.0,
					y: 124.0,
				},
				padding: {
					x: 9.07612,
					y: 2.07612038,
					z: 10.0761185,
					w: 1.02674866,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Mosscreep Tool 2',
			displayName: 'Tools.MOSSCREEP_TOOL_2_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_mossmedal_second_9_142x142_0',
				nameShort: 'T_mossmedal_second',
				size: {
					x: 142.0,
					y: 142.0,
				},
				padding: {
					x: 12.07612,
					y: 10.0129128,
					z: 12.0267487,
					w: 9.076126,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Lava Charm',
			displayName: 'Tools.LAVA_CHARM_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'Hornet_T_lava_charm_7_124x149_2',
				nameShort: 'Hornet_T_lava_charm',
				size: {
					x: 124.0,
					y: 149.0,
				},
				padding: {
					x: 6.026751,
					y: 1.026751,
					z: 5.02674866,
					w: 0.0761261,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Bell Bind',
			displayName: 'Tools.BELL_BIND_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'Hornet_icon_0001_T_bell_shield_10_126x157_2',
				nameShort: 'Hornet_icon_0001_T_bell_shield',
				size: {
					x: 126.0,
					y: 157.0,
				},
				padding: {
					x: 5.026751,
					y: 5.07612038,
					z: 5.02674866,
					w: 11.06102,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Poison Pouch',
			displayName: 'Tools.POISON_POUCH_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_poison_pouch_8_124x134_1',
				nameShort: 'T_poison_pouch',
				size: {
					x: 124.0,
					y: 134.0,
				},
				padding: {
					x: 1.0761205,
					y: 1.0761205,
					z: 2.07611847,
					w: 1.0761261,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Fractured Mask',
			displayName: 'Tools.FRACTURED_MASK_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'Hornet_T_fractured_mask_10_142x144_0',
				nameShort: 'Hornet_T_fractured_mask',
				size: {
					x: 142.0,
					y: 144.0,
				},
				padding: {
					x: 4.026751,
					y: 2.026751,
					z: 2.02674866,
					w: 7.076126,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Multibind',
			displayName: 'Tools.MULTIBIND_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_multi_bind_29_141x166_1',
				nameShort: 'T_multi_bind',
				size: {
					x: 141.0,
					y: 166.0,
				},
				padding: {
					x: 4.07612038,
					y: 9.07612,
					z: 3.076126,
					w: 9.076126,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'White Ring',
			displayName: 'Tools.WHITE_RING_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_icon_white_ring_19_149x165_2',
				nameShort: 'T_icon_white_ring',
				size: {
					x: 149.0,
					y: 165.0,
				},
				padding: {
					x: 7.07612038,
					y: 10.0,
					z: 9.076126,
					w: 11.0761261,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Brolly Spike',
			displayName: 'Tools.BROLLYSPIKE_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_brolly_spike_7_149x136_0',
				nameShort: 'T_brolly_spike',
				size: {
					x: 149.0,
					y: 136.0,
				},
				padding: {
					x: 0.0761204958,
					y: 1.06585836,
					z: 0.0761261,
					w: 4.05131531,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Quickbind',
			displayName: 'Tools.QUICKBIND_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_quick_bind_64_127x132_2',
				nameShort: 'T_quick_bind',
				size: {
					x: 127.0,
					y: 132.0,
				},
				padding: {
					x: 6.026751,
					y: 6.05131674,
					z: 0.05973053,
					w: 0.0,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Spool Extender',
			displayName: 'Tools.SPOOL_EXTENDER_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_spool_bar_extender_8_117x158_1',
				nameShort: 'T_spool_bar_extender',
				size: {
					x: 117.0,
					y: 158.0,
				},
				padding: {
					x: 5.04290771,
					y: 6.07612038,
					z: 5.04290771,
					w: 5.02674866,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Reserve Bind',
			displayName: 'Tools.RESERVE_BIND_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_focus_spool_22_155x142_0',
				nameShort: 'T_focus_spool',
				size: {
					x: 155.0,
					y: 142.0,
				},
				padding: {
					x: 8.051316,
					y: 9.042908,
					z: 9.026749,
					w: 8.076126,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Dazzle Bind',
			displayName: 'Tools.DAZZLE_BIND_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_dazzle_bind_13_120x155_0',
				nameShort: 'T_dazzle_bind',
				size: {
					x: 120.0,
					y: 155.0,
				},
				padding: {
					x: 8.07612,
					y: 4.026751,
					z: 6.07611847,
					w: 4.076126,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Dazzle Bind Upgraded',
			displayName: 'Tools.DAZZLE_BIND_UPG_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_dazzle_bind_upg_26_158x168_0',
				nameShort: 'T_dazzle_bind_upg',
				size: {
					x: 158.0,
					y: 168.0,
				},
				padding: {
					x: 4.026751,
					y: 5.07612038,
					z: 2.076126,
					w: 5.076126,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Revenge Crystal',
			displayName: 'Tools.REVENGE_CRYSTAL_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_revenge_crystal_10_148x144_1',
				nameShort: 'T_revenge_crystal',
				size: {
					x: 148.0,
					y: 144.0,
				},
				padding: {
					x: 10.07612,
					y: 4.07612038,
					z: 7.02674866,
					w: 5.076126,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Thief Claw',
			displayName: 'Tools.THIEF_CLAW_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'Thief_Claw_8_140x164_7',
				nameShort: 'Thief_Claw',
				size: {
					x: 140.0,
					y: 164.0,
				},
				padding: {
					x: 0.0267509818,
					y: 9.004041,
					z: 6.076126,
					w: 20.0429077,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Zap Imbuement',
			displayName: 'Tools.ZAP_IMBUEMENT_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_zap_imbuement_8_139x142_3',
				nameShort: 'T_zap_imbuement',
				size: {
					x: 139.0,
					y: 142.0,
				},
				padding: {
					x: 0.0761204958,
					y: 1.0761205,
					z: 1.02674866,
					w: 0.0,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Quick Sling',
			displayName: 'Tools.QUICK_SLING_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_quick_sling_7_122x140_0',
				nameShort: 'T_quick_sling',
				size: {
					x: 122.0,
					y: 140.0,
				},
				padding: {
					x: 3.026751,
					y: 4.011117,
					z: 4.0362854,
					w: 4.02674866,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Maggot Charm',
			displayName: 'Tools.MAGGOT_CHARM_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'poultice_pouch_icon_17_166x164_1',
				nameShort: 'poultice_pouch_icon',
				size: {
					x: 166.0,
					y: 164.0,
				},
				padding: {
					x: 16.02675,
					y: 19.02675,
					z: 14.0761261,
					w: 14.0267487,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Longneedle',
			displayName: 'Tools.LONGNEEDLE_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_longneedle_8_135x152_0',
				nameShort: 'T_longneedle',
				size: {
					x: 135.0,
					y: 152.0,
				},
				padding: {
					x: 13.0477047,
					y: 0.0761204958,
					z: 14.0761185,
					w: 3.02674866,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Wisp Lantern',
			displayName: 'Tools.WISP_LANTERN_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_wisp_lantern_16_132x158_0',
				nameShort: 'T_wisp_lantern',
				size: {
					x: 132.0,
					y: 158.0,
				},
				padding: {
					x: 1.01291251,
					y: 9.026751,
					z: 1.01290894,
					w: 4.02674866,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Flea Charm',
			displayName: 'Tools.FLEA_CHARM_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'Flea_Egg_9_150x182_1',
				nameShort: 'Flea_Egg',
				size: {
					x: 150.0,
					y: 182.0,
				},
				padding: {
					x: 8.07612,
					y: 19.07612,
					z: 9.004044,
					w: 15.0267487,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Pinstress Tool',
			displayName: 'Tools.PINSTRESS_NAME',
			type: 'Blue',
			toolSprite: {
				name: 'T_pinstress_tool_24_149x164_0',
				nameShort: 'T_pinstress_tool',
				size: {
					x: 149.0,
					y: 164.0,
				},
				padding: {
					x: 18.02675,
					y: 6.07612038,
					z: 10.0761261,
					w: 8.042908,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Compass',
			displayName: 'Tools.COMPASS_NAME',
			type: 'Yellow',
			toolSprite: {
				name: 'T_Compass_9_134x134_0',
				nameShort: 'T_Compass',
				size: {
					x: 134.0,
					y: 134.0,
				},
				padding: {
					x: 2.03350043,
					y: 4.026751,
					z: 2.076126,
					w: 12.0267487,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Bone Necklace',
			displayName: 'Tools.BONE_NECKLACE_NAME',
			type: 'Yellow',
			toolSprite: {
				name: 'Hornet_Bone_Necklace_9_120x120_0',
				nameShort: 'Hornet_Bone_Necklace',
				size: {
					x: 120.0,
					y: 120.0,
				},
				padding: {
					x: 0.0,
					y: 0.0,
					z: 0.07611847,
					w: 0.0,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Rosary Magnet',
			displayName: 'Tools.ROSARY_MAGNET_NAME',
			type: 'Yellow',
			toolSprite: {
				name: 'T_rosary_magnet_6_150x154_0',
				nameShort: 'T_rosary_magnet',
				size: {
					x: 150.0,
					y: 154.0,
				},
				padding: {
					x: 17.07612,
					y: 17.02675,
					z: 15.0761261,
					w: 16.0267487,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Weighted Anklet',
			displayName: 'Tools.WEIGHTED_ANKLET_NAME',
			type: 'Yellow',
			toolSprite: {
				name: 'T_weighted_anklet_16_139x137_0',
				nameShort: 'T_weighted_anklet',
				size: {
					x: 139.0,
					y: 137.0,
				},
				padding: {
					x: 3.01291251,
					y: 0.0,
					z: 3.012909,
					w: 9.076118,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Barbed Wire',
			displayName: 'Tools.BARBED_WIRE_NAME',
			type: 'Yellow',
			toolSprite: {
				name: 'T_barbed_wire_12_213x191_0',
				nameShort: 'T_barbed_wire',
				size: {
					x: 213.0,
					y: 191.0,
				},
				padding: {
					x: 27.07612,
					y: 34.0761223,
					z: 29.0761261,
					w: 29.0267487,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Dead Mans Purse',
			displayName: 'Tools.DEAD_MANS_PURSE_NAME',
			type: 'Yellow',
			toolSprite: {
				name: 'T_dead_purse_8_132x136_0',
				nameShort: 'T_dead_purse',
				size: {
					x: 132.0,
					y: 136.0,
				},
				padding: {
					x: 5.07612038,
					y: 3.026751,
					z: 4.06211853,
					w: 2.02674866,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Shell Satchel',
			displayName: 'Tools.SHELL_SATCHEL_NAME',
			type: 'Yellow',
			toolSprite: {
				name: 'T_shell_satchel_8_146x142_2',
				nameShort: 'T_shell_satchel',
				size: {
					x: 146.0,
					y: 142.0,
				},
				padding: {
					x: 7.07612038,
					y: 8.026751,
					z: 9.076126,
					w: 9.076126,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Magnetite Dice',
			displayName: 'Tools.MAGNETITE_DICE_NAME',
			type: 'Yellow',
			toolSprite: {
				name: '_0006_I_magnetite_dice_9_141x142_0',
				nameShort: '_0006_I_magnetite_dice',
				size: {
					x: 141.0,
					y: 142.0,
				},
				padding: {
					x: 5.07612038,
					y: 5.026751,
					z: 5.02674866,
					w: 5.076126,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Scuttlebrace',
			displayName: 'Tools.SCUTTLEBRACE_NAME',
			type: 'Yellow',
			toolSprite: {
				name: 'T_steel_spine_7_153x127_0',
				nameShort: 'T_steel_spine',
				size: {
					x: 153.0,
					y: 127.0,
				},
				padding: {
					x: 0.00884819,
					y: 3.026751,
					z: 0.0267486572,
					w: 9.051315,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Wallcling',
			displayName: 'Tools.WALLCLING_NAME',
			type: 'Yellow',
			toolSprite: {
				name: 'T_longneedle_old1_13_160x148_2',
				nameShort: 'T_longneedle_old1',
				size: {
					x: 160.0,
					y: 148.0,
				},
				padding: {
					x: 6.07612038,
					y: 4.01291275,
					z: 7.0362854,
					w: 4.012909,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Musician Charm',
			displayName: 'Tools.MUSICIAN_CHARM_NAME',
			type: 'Yellow',
			toolSprite: {
				name: 'T_attunement_charm_7_135x149_6',
				nameShort: 'T_attunement_charm',
				size: {
					x: 135.0,
					y: 149.0,
				},
				padding: {
					x: 0.0,
					y: 0.0,
					z: 8.076118,
					w: 9.026749,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Sprintmaster',
			displayName: 'Tools.SPRINTMASTER_NAME',
			type: 'Yellow',
			toolSprite: {
				name: 'T_icon_sprintmaster_12_133x151_2',
				nameShort: 'T_icon_sprintmaster',
				size: {
					x: 133.0,
					y: 151.0,
				},
				padding: {
					x: 2.026751,
					y: 5.04290771,
					z: 2.04290771,
					w: 5.033493,
				},
			},
			alternateUnlockedTest: null,
		},
		{
			id: 'Thief Charm',
			displayName: 'Tools.THIEF_CHARM_NAME',
			type: 'Yellow',
			toolSprite: {
				name: 'Thief_Brooch_10_159x139_3',
				nameShort: 'Thief_Brooch',
				size: {
					x: 159.0,
					y: 139.0,
				},
				padding: {
					x: 20.07612,
					y: 11.07612,
					z: 6.02674866,
					w: 14.0429077,
				},
			},
			alternateUnlockedTest: null,
		},
	],
};
export type ToolItemNameSilk =
	| 'Silk Spear'
	| 'Thread Sphere'
	| 'Parry'
	| 'Silk Charge'
	| 'Silk Bomb'
	| 'Silk Boss Needle'
	| 'Straight Pin'
	| 'Tri Pin'
	| 'Sting Shard'
	| 'Tack'
	| 'Harpoon'
	| 'Curve Claws'
	| 'Curve Claws Upgraded'
	| 'Shakra Ring'
	| 'Pimpilo'
	| 'Conch Drill'
	| 'WebShot Forge'
	| 'WebShot Architect'
	| 'WebShot Weaver'
	| 'Screw Attack'
	| 'Cogwork Saw'
	| 'Cogwork Flier'
	| 'Rosary Cannon'
	| 'Lightning Rod'
	| 'Flintstone'
	| 'Silk Snare'
	| 'Flea Brew'
	| 'Lifeblood Syringe'
	| 'Extractor'
	| 'Mosscreep Tool 1'
	| 'Mosscreep Tool 2'
	| 'Lava Charm'
	| 'Bell Bind'
	| 'Poison Pouch'
	| 'Fractured Mask'
	| 'Multibind'
	| 'White Ring'
	| 'Brolly Spike'
	| 'Quickbind'
	| 'Spool Extender'
	| 'Reserve Bind'
	| 'Dazzle Bind'
	| 'Dazzle Bind Upgraded'
	| 'Revenge Crystal'
	| 'Thief Claw'
	| 'Zap Imbuement'
	| 'Quick Sling'
	| 'Maggot Charm'
	| 'Longneedle'
	| 'Wisp Lantern'
	| 'Flea Charm'
	| 'Pinstress Tool'
	| 'Compass'
	| 'Bone Necklace'
	| 'Rosary Magnet'
	| 'Weighted Anklet'
	| 'Barbed Wire'
	| 'Dead Mans Purse'
	| 'Shell Satchel'
	| 'Magnetite Dice'
	| 'Scuttlebrace'
	| 'Wallcling'
	| 'Musician Charm'
	| 'Sprintmaster'
	| 'Thief Charm';

export const toolItemIdToNameSilk: Map<number, ToolItemNameSilk> = new Map([
	[1, 'Silk Spear'],
	[2, 'Thread Sphere'],
	[3, 'Parry'],
	[4, 'Silk Charge'],
	[5, 'Silk Bomb'],
	[6, 'Silk Boss Needle'],
	[7, 'Straight Pin'],
	[8, 'Tri Pin'],
	[9, 'Sting Shard'],
	[10, 'Tack'],
	[11, 'Harpoon'],
	[12, 'Curve Claws'],
	[13, 'Curve Claws Upgraded'],
	[14, 'Shakra Ring'],
	[15, 'Pimpilo'],
	[16, 'Conch Drill'],
	[17, 'WebShot Forge'],
	[18, 'WebShot Architect'],
	[19, 'WebShot Weaver'],
	[20, 'Screw Attack'],
	[21, 'Cogwork Saw'],
	[22, 'Cogwork Flier'],
	[23, 'Rosary Cannon'],
	[24, 'Lightning Rod'],
	[25, 'Flintstone'],
	[26, 'Silk Snare'],
	[27, 'Flea Brew'],
	[28, 'Lifeblood Syringe'],
	[29, 'Extractor'],
	[30, 'Mosscreep Tool 1'],
	[31, 'Mosscreep Tool 2'],
	[32, 'Lava Charm'],
	[33, 'Bell Bind'],
	[34, 'Poison Pouch'],
	[35, 'Fractured Mask'],
	[36, 'Multibind'],
	[37, 'White Ring'],
	[38, 'Brolly Spike'],
	[39, 'Quickbind'],
	[40, 'Spool Extender'],
	[41, 'Reserve Bind'],
	[42, 'Dazzle Bind'],
	[43, 'Dazzle Bind Upgraded'],
	[44, 'Revenge Crystal'],
	[45, 'Thief Claw'],
	[46, 'Zap Imbuement'],
	[47, 'Quick Sling'],
	[48, 'Maggot Charm'],
	[49, 'Longneedle'],
	[50, 'Wisp Lantern'],
	[51, 'Flea Charm'],
	[52, 'Pinstress Tool'],
	[53, 'Compass'],
	[54, 'Bone Necklace'],
	[55, 'Rosary Magnet'],
	[56, 'Weighted Anklet'],
	[57, 'Barbed Wire'],
	[58, 'Dead Mans Purse'],
	[59, 'Shell Satchel'],
	[60, 'Magnetite Dice'],
	[61, 'Scuttlebrace'],
	[62, 'Wallcling'],
	[63, 'Musician Charm'],
	[64, 'Sprintmaster'],
	[65, 'Thief Charm'],
]);
export const toolItemNamesSilk: ToolItemNameSilk[] = toolItemIdToNameSilk.values().toArray();
