/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */

export type ToolLiquidNameSilk = 'Flea Brew' | 'Lifeblood Syringe';

const list = [
	{
		id: 'Flea Brew',
	},
	{
		id: 'Lifeblood Syringe',
	},
];
export type ToolLiquidSilk = (typeof list)[number];
export const toolLiquidSilk = {
	list,
	byName: Object.fromEntries(list.map((it: any) => [it.id, it])) as Record<ToolLiquidNameSilk, ToolLiquidSilk>,
};

export const toolLiquidIdToNameSilk: Map<number, ToolLiquidNameSilk> = new Map([
	[1, 'Flea Brew'],
	[2, 'Lifeblood Syringe'],
]);
export const toolLiquidNamesSilk: ToolLiquidNameSilk[] = toolLiquidIdToNameSilk.values().toArray();
