/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
export const transitionGateSilk = {
	all: [
		{
			id: 'bot1',
		},
		{
			id: 'bot1 firstEntry',
		},
		{
			id: 'bot2',
		},
		{
			id: 'bot3',
		},
		{
			id: 'bot4',
		},
		{
			id: 'bot5',
		},
		{
			id: 'bot6',
		},
		{
			id: 'bot7',
		},
		{
			id: 'bot8',
		},
		{
			id: 'door1',
		},
		{
			id: 'door1 firstExit',
		},
		{
			id: 'door2',
		},
		{
			id: 'door3',
		},
		{
			id: 'door4',
		},
		{
			id: 'door5',
		},
		{
			id: 'door_act3_wakeUp',
		},
		{
			id: 'door_arriveFromTower',
		},
		{
			id: 'door_caravanTravelEnd',
		},
		{
			id: 'door_centipedeExit',
		},
		{
			id: 'door_cinematicEnd',
		},
		{
			id: 'door_curseSequenceEnd',
		},
		{
			id: 'door_cutsceneEndLaceTower',
		},
		{
			id: 'door_cutscenePosition',
		},
		{
			id: 'door_enterRedMemory Beast',
		},
		{
			id: 'door_enterRedMemory Hive',
		},
		{
			id: 'door_enterRedMemory Weaver',
		},
		{
			id: 'door_entry',
		},
		{
			id: 'door_fastTravelExit',
		},
		{
			id: 'door_memoryEnd',
		},
		{
			id: 'door_ritualEnd',
		},
		{
			id: 'door_slabCaged',
		},
		{
			id: 'door_test',
		},
		{
			id: 'door_tubeEnter',
		},
		{
			id: 'door_wakeInMemory',
		},
		{
			id: 'door_wakeInRedMemory Beast',
		},
		{
			id: 'door_wakeInRedMemory Hive',
		},
		{
			id: 'door_wakeInRedMemory Root',
		},
		{
			id: 'door_wakeInRedMemory Weaver',
		},
		{
			id: 'door_wakeOnGround',
		},
		{
			id: 'left1',
		},
		{
			id: 'left2',
		},
		{
			id: 'left3',
		},
		{
			id: 'left4',
		},
		{
			id: 'left5',
		},
		{
			id: 'left6',
		},
		{
			id: 'left7',
		},
		{
			id: 'left8',
		},
		{
			id: 'left_firstEntrance',
		},
		{
			id: 'right1',
		},
		{
			id: 'right2',
		},
		{
			id: 'right3',
		},
		{
			id: 'right4',
		},
		{
			id: 'right5',
		},
		{
			id: 'right6',
		},
		{
			id: 'right7',
		},
		{
			id: 'right8',
		},
		{
			id: 'right9',
		},
		{
			id: 'right_cutsceneEntry',
		},
		{
			id: 'top1',
		},
		{
			id: 'top1 (1)',
		},
		{
			id: 'top2',
		},
		{
			id: 'top2 extra',
		},
		{
			id: 'top3',
		},
		{
			id: 'top4',
		},
		{
			id: 'top5',
		},
		{
			id: 'top6',
		},
		{
			id: 'top7',
		},
		{
			id: 'top8',
		},
	],
};
export type TransitionGateNameSilk =
	| 'bot1'
	| 'bot1 firstEntry'
	| 'bot2'
	| 'bot3'
	| 'bot4'
	| 'bot5'
	| 'bot6'
	| 'bot7'
	| 'bot8'
	| 'door1'
	| 'door1 firstExit'
	| 'door2'
	| 'door3'
	| 'door4'
	| 'door5'
	| 'door_act3_wakeUp'
	| 'door_arriveFromTower'
	| 'door_caravanTravelEnd'
	| 'door_centipedeExit'
	| 'door_cinematicEnd'
	| 'door_curseSequenceEnd'
	| 'door_cutsceneEndLaceTower'
	| 'door_cutscenePosition'
	| 'door_enterRedMemory Beast'
	| 'door_enterRedMemory Hive'
	| 'door_enterRedMemory Weaver'
	| 'door_entry'
	| 'door_fastTravelExit'
	| 'door_memoryEnd'
	| 'door_ritualEnd'
	| 'door_slabCaged'
	| 'door_test'
	| 'door_tubeEnter'
	| 'door_wakeInMemory'
	| 'door_wakeInRedMemory Beast'
	| 'door_wakeInRedMemory Hive'
	| 'door_wakeInRedMemory Root'
	| 'door_wakeInRedMemory Weaver'
	| 'door_wakeOnGround'
	| 'left1'
	| 'left2'
	| 'left3'
	| 'left4'
	| 'left5'
	| 'left6'
	| 'left7'
	| 'left8'
	| 'left_firstEntrance'
	| 'right1'
	| 'right2'
	| 'right3'
	| 'right4'
	| 'right5'
	| 'right6'
	| 'right7'
	| 'right8'
	| 'right9'
	| 'right_cutsceneEntry'
	| 'top1'
	| 'top1 (1)'
	| 'top2'
	| 'top2 extra'
	| 'top3'
	| 'top4'
	| 'top5'
	| 'top6'
	| 'top7'
	| 'top8';

export const transitionGateIdToNameSilk: Map<number, TransitionGateNameSilk> = new Map([
	[1, 'bot1'],
	[2, 'bot1 firstEntry'],
	[3, 'bot2'],
	[4, 'bot3'],
	[5, 'bot4'],
	[6, 'bot5'],
	[7, 'bot6'],
	[8, 'bot7'],
	[9, 'bot8'],
	[10, 'door1'],
	[11, 'door1 firstExit'],
	[12, 'door2'],
	[13, 'door3'],
	[14, 'door4'],
	[15, 'door5'],
	[16, 'door_act3_wakeUp'],
	[17, 'door_arriveFromTower'],
	[18, 'door_caravanTravelEnd'],
	[19, 'door_centipedeExit'],
	[20, 'door_cinematicEnd'],
	[21, 'door_curseSequenceEnd'],
	[22, 'door_cutsceneEndLaceTower'],
	[23, 'door_cutscenePosition'],
	[24, 'door_enterRedMemory Beast'],
	[25, 'door_enterRedMemory Hive'],
	[26, 'door_enterRedMemory Weaver'],
	[27, 'door_entry'],
	[28, 'door_fastTravelExit'],
	[29, 'door_memoryEnd'],
	[30, 'door_ritualEnd'],
	[31, 'door_slabCaged'],
	[32, 'door_test'],
	[33, 'door_tubeEnter'],
	[34, 'door_wakeInMemory'],
	[35, 'door_wakeInRedMemory Beast'],
	[36, 'door_wakeInRedMemory Hive'],
	[37, 'door_wakeInRedMemory Root'],
	[38, 'door_wakeInRedMemory Weaver'],
	[39, 'door_wakeOnGround'],
	[40, 'left1'],
	[41, 'left2'],
	[42, 'left3'],
	[43, 'left4'],
	[44, 'left5'],
	[45, 'left6'],
	[46, 'left7'],
	[47, 'left8'],
	[48, 'left_firstEntrance'],
	[49, 'right1'],
	[50, 'right2'],
	[51, 'right3'],
	[52, 'right4'],
	[53, 'right5'],
	[54, 'right6'],
	[55, 'right7'],
	[56, 'right8'],
	[57, 'right9'],
	[58, 'right_cutsceneEntry'],
	[59, 'top1'],
	[60, 'top1 (1)'],
	[61, 'top2'],
	[62, 'top2 extra'],
	[63, 'top3'],
	[64, 'top4'],
	[65, 'top5'],
	[66, 'top6'],
	[67, 'top7'],
	[68, 'top8'],
]);
export const transitionGateNamesSilk: TransitionGateNameSilk[] = transitionGateIdToNameSilk.values().toArray();
