/**
 * This file is auto-generated by a script (See ./scripts/*). Do not edit directly.
 */
import type { SupportedLanguageSilk } from './supported-languages-silk.ts';
import { assertNever } from '~/lib/util/other.ts';

export interface LocalizationDataSilk {
	['Map Zones.BONETOWN']: string;
	['Map Zones.WEAVER_SHRINE']: string;
	['Map Zones.BONECHURCH']: string;
	['Map Zones.MOSS_CAVE']: string;
	['Map Zones.PATH_OF_BONE']: string;
	['Map Zones.BONETOWN_GRAVEYARD']: string;
	['Map Zones.SHELLWOOD_THICKET']: string;
	['Map Zones.CRAWLSPACE']: string;
	['Map Zones.MOSSTOWN']: string;
	['Map Zones.BELLTOWN']: string;
	['Map Zones.HUNTERS_NEST']: string;
	['Map Zones.DOCKS']: string;
	['Map Zones.WILDS']: string;
	['Map Zones.PILGRIMS_REST']: string;
	['Map Zones.GREYMOOR']: string;
	['Map Zones.DUSTPENS']: string;
	['Map Zones.WISP']: string;
	['Map Zones.CRAW_LAKE']: string;
	['Map Zones.CLOVER']: string;
	['Map Zones.HALFWAY_HOUSE']: string;
	['Map Zones.SWAMP']: string;
	['Map Zones.UNDERSTORE']: string;
	['Map Zones.AQUEDUCT']: string;
	['Map Zones.MUCKVILLAGE']: string;
	['Map Zones.LIBRARY']: string;
	['Map Zones.ORGAN']: string;
	['Map Zones.ARBORIUM']: string;
	['Map Zones.WHITELAKE']: string;
	['Map Zones.FLEATOPIA']: string;
	['Map Zones.JUDGE_STEPS']: string;
	['Map Zones.RED_CORAL_GORGE']: string;
	['Map Zones.FRONT_GATE']: string;
	['Map Zones.RED_CORAL_TOWER']: string;
	['Map Zones.VOLTNEST']: string;
	['Map Zones.HIGH_HALLS']: string;
	['Map Zones.PEAK']: string;
	['Map Zones.THE_SLAB']: string;
	['Map Zones.ICECORE']: string;
	['Map Zones.WARD']: string;
	['Map Zones.COG_CORE_SHORT']: string;
	['Map Zones.BATHHOUSE']: string;
	['Map Zones.HANG']: string;
	['Map Zones.LIBRARY_SHORT']: string;
	['Map Zones.CITADEL_STATION']: string;
	['Map Zones.CITADEL_STAGE']: string;
	['Map Zones.ENCLAVE']: string;
	['Map Zones.CAULDRON']: string;
	['Map Zones.CRADLE']: string;
	['Map Zones.CITADEL_FORUM']: string;
	['Map Zones.COG_CORE']: string;
	['Map Zones.ABYSS']: string;
	['Tools.CREST_HUNTER_NAME']: string;
	['Tools.CREST_REAPER_NAME']: string;
	['Tools.CREST_PILGRIM_NAME']: string;
	['Tools.CREST_WARRIOR_NAME']: string;
	['Tools.CREST_WITCH_NAME']: string;
	['Tools.CREST_TOOLMASTER_NAME']: string;
	['Tools.CREST_SPELL_NAME']: string;
	['Tools.CREST_CURSE_NAME']: string;
	['Map Zones.ABOVE_CRADLE']: string;
	['Map Zones.BELLHOME']: string;
	['Map Zones.BELLTOWN_HAUNTED']: string;
	['Map Zones.BELLVEIN']: string;
	['Map Zones.CITADELSHRINE']: string;
	['Map Zones.CITY_OF_SONG']: string;
	['Map Zones.CORAL_CAVERNS']: string;
	['Map Zones.DUST_MAZE']: string;
	['Map Zones.EXTRA_TUBEHUB']: string;
	['Map Zones.FLEA_FESTIVAL']: string;
	['Map Zones.GLOOM']: string;
	['Map Zones.MEMORY']: string;
	['Map Zones.MEMORY_RED']: string;
	['Map Zones.NONE']: string;
	['Map Zones.PHARLOOM_BAY']: string;
	['Map Zones.SPRINTMASTER_CAVE']: string;
	['Map Zones.SURFACE']: string;
	['Map Zones.TEST_AREA']: string;
}

export async function loadLangSilk(lang: SupportedLanguageSilk): Promise<LocalizationDataSilk> {
	switch (lang) {
		case 'ZH':
			return (await import('./localization-ZH.generated')).default;
		case 'ZH_TW':
			return (await import('./localization-ZH_TW.generated')).default;
		case 'RU':
			return (await import('./localization-RU.generated')).default;
		case 'PT':
			return (await import('./localization-PT.generated')).default;
		case 'KO':
			return (await import('./localization-KO.generated')).default;
		case 'JA':
			return (await import('./localization-JA.generated')).default;
		case 'IT':
			return (await import('./localization-IT.generated')).default;
		case 'FR':
			return (await import('./localization-FR.generated')).default;
		case 'ES':
			return (await import('./localization-ES.generated')).default;
		case 'EN':
			return (await import('./localization-EN.generated')).default;
		case 'DE':
			return (await import('./localization-DE.generated')).default;
		default:
			return assertNever(lang);
	}
}
